-- 012_exercise_library_seed_chest.sql
-- เพิ่มท่ากลุ่ม "อก" อีก 37 ท่า (ของเดิมมี 8 ท่าอยู่แล้ว: bench-press, cable-crossover, chest-dip,
-- decline-bench-press, dumbbell-bench-press, dumbbell-fly, incline-bench-press, push-up — เช็คแล้วไม่ชนกับชุดนี้)
-- ครอบคลุมครบ 4 อุปกรณ์หลัก: บาร์เบล(7) ดัมเบล(9) เครื่อง(7) เคเบิล(6) น้ำหนักตัว(8)
-- ON CONFLICT (id) DO NOTHING — รันซ้ำได้ปลอดภัย ไม่ทับแถวเดิมถ้ามี id ซ้ำโดยบังเอิญ

insert into public.exercise_library
  (id, name, name_th, aliases, primary_muscle, secondary_muscles, equipment, icon, instructions, is_custom)
values
  -- ===== บาร์เบล (7) =====
  ('floor-press-barbell', 'Barbell Floor Press', 'บาร์เบลฟลอร์เพรส',
    array['floor press', 'ฟลอร์เพรส'], 'อก', array['ไหล่','แขน'], 'บาร์เบล', '🏋️',
    array['นอนราบกับพื้น ต้นแขนแตะพื้นตอนล่างสุดของจังหวะ', 'ตัดระยะ ROM ช่วยจุดล็อกช่วงบนของเบนช์เพรส'], false),
  ('guillotine-press', 'Guillotine Press', 'กิโยตินเพรส',
    array['neck press', 'เพรสลงคอ'], 'อก', array['ไหล่'], 'บาร์เบล', '🏋️',
    array['วางบาร์ลงใกล้ลำคอ/คาง ไม่ใช่หน้าอกกลาง', 'ควบคุมน้ำหนักเบาก่อน เสี่ยงไหล่ถ้าฟอร์มไม่นิ่ง'], false),
  ('spoto-press', 'Spoto Press', 'สโปโตเพรส',
    array['pause press เหนือหน้าอก'], 'อก', array['ไหล่','แขน'], 'บาร์เบล', '🏋️',
    array['ลดบาร์ลงจนเกือบแตะอก ค้าง 1-2 วิเหนือหน้าอกก่อนดันขึ้น', 'ตัดแรงเด้ง ช่วยสร้างความแข็งแรงกลางจังหวะ'], false),
  ('larsen-press', 'Larsen Press', 'ลาร์เซนเพรส',
    array['feet up bench press', 'เพรสยกขาลอย'], 'อก', array['แกนกลางลำตัว'], 'บาร์เบล', '🏋️',
    array['ยกเท้าลอยจากพื้นตลอดเซ็ต ตัดแรงเหวี่ยงจากขา', 'เน้นควบคุมด้วยอกและแกนกลางล้วนๆ'], false),
  ('wide-grip-bench-press', 'Wide-Grip Bench Press', 'เบนช์เพรสจับกว้าง',
    array['wide grip bench'], 'อก', array['ไหล่'], 'บาร์เบล', '🏋️',
    array['จับบาร์กว้างกว่าค่าไหล่ปกติ 1-2 กำ', 'ROM สั้นลง เน้นกล้ามอกด้านนอกมากขึ้น'], false),
  ('reverse-grip-bench-press', 'Reverse-Grip Bench Press', 'เบนช์เพรสจับคว่ำ',
    array['underhand bench press', 'เบนช์เพรสจับหงาย'], 'อก', array['แขน'], 'บาร์เบล', '🏋️',
    array['จับบาร์แบบมือหงาย (supinated)', 'เน้นอกส่วนบนมากกว่าจับปกติ ระวังข้อมือ'], false),
  ('pin-press-barbell', 'Pin Press', 'พินเพรส',
    array['rack press', 'เพรสจากหมุด'], 'อก', array['ไหล่','แขน'], 'บาร์เบล', '🏋️',
    array['วางบาร์บนหมุด Power Rack ที่ระดับต่ำกว่าจุดติด ดันขึ้นจากจุดหยุดนิ่ง', 'ไม่มีแรงเด้ง เหมาะฝึกพลังจุดที่อ่อนที่สุด'], false),

  -- ===== ดัมเบล (9) =====
  ('incline-dumbbell-press', 'Incline Dumbbell Press', 'อินไคลน์ดัมเบลเพรส',
    array['incline db press'], 'อก', array['ไหล่','แขน'], 'ดัมเบล', '💪',
    array['ปรับม้านั่งเอียง 30-45 องศา', 'เน้นอกส่วนบนมากกว่าเพรสราบ'], false),
  ('decline-dumbbell-press', 'Decline Dumbbell Press', 'เดคลายน์ดัมเบลเพรส',
    array['decline db press'], 'อก', array['ไหล่','แขน'], 'ดัมเบล', '💪',
    array['ปรับม้านั่งเอียงลง เน้นอกส่วนล่าง', 'ล็อกขาไว้กับที่พยุงตัวให้มั่นคง'], false),
  ('incline-dumbbell-fly', 'Incline Dumbbell Fly', 'อินไคลน์ดัมเบลฟลาย',
    array['incline fly'], 'อก', array['ไหล่'], 'ดัมเบล', '💪',
    array['แขนโค้งงอเล็กน้อยตลอดเซ็ต ไม่ล็อกข้อศอก', 'กางออกจนรู้สึกยืดที่หน้าอกบน ไม่ต่ำเกินระดับไหล่'], false),
  ('decline-dumbbell-fly', 'Decline Dumbbell Fly', 'เดคลายน์ดัมเบลฟลาย',
    array['decline fly'], 'อก', array['ไหล่'], 'ดัมเบล', '💪',
    array['ม้านั่งเอียงลง กางแขนเน้นยืดอกส่วนล่าง', 'คุมจังหวะช้าๆ ไม่เหวี่ยง'], false),
  ('single-arm-dumbbell-bench-press', 'Single-Arm Dumbbell Bench Press', 'ดัมเบลเบนช์เพรสข้างเดียว',
    array['single arm db press'], 'อก', array['แกนกลางลำตัว','ไหล่'], 'ดัมเบล', '💪',
    array['ทำทีละข้าง อีกข้างล็อกลำตัวไม่ให้บิด', 'ฝึกความมั่นคงของแกนกลางไปพร้อมอก'], false),
  ('dumbbell-floor-press', 'Dumbbell Floor Press', 'ดัมเบลฟลอร์เพรส',
    array['db floor press'], 'อก', array['แขน'], 'ดัมเบล', '💪',
    array['นอนกับพื้น ต้นแขนแตะพื้นตอนล่างสุด', 'ROM สั้น เหมาะคนไหล่มีปัญหาหลีกเลี่ยง full ROM'], false),
  ('dumbbell-pullover', 'Dumbbell Pullover', 'ดัมเบลพูลโอเวอร์',
    array['pullover'], 'อก', array['หลัง'], 'ดัมเบล', '💪',
    array['นอนขวางม้านั่งหรือนอนราบ ยกดัมเบลจากเหนือศีรษะมาที่หน้าอก', 'ยืดซี่โครง/lats ไปพร้อมกัน คุมน้ำหนักเบาก่อน'], false),
  ('svend-press', 'Svend Press', 'สเวนด์เพรส',
    array['plate squeeze press'], 'อก', array['ไหล่'], 'ดัมเบล', '💪',
    array['ประกบแผ่นน้ำหนัก/ดัมเบลด้วยสองมือ บีบแน่นตลอดเซ็ต', 'ดันออกจากอกตรงระดับหน้าอก เน้นการบีบมากกว่าน้ำหนัก'], false),
  ('neutral-grip-dumbbell-press', 'Neutral-Grip Dumbbell Press', 'ดัมเบลเพรสจับคว่ำขนาน',
    array['hammer grip press'], 'อก', array['ไหล่','แขน'], 'ดัมเบล', '💪',
    array['จับดัมเบลแบบฝ่ามือหันเข้าหากันตลอดเซ็ต', 'ลดแรงกดข้อไหล่ เหมาะคนไหล่ไม่สบาย'], false),

  -- ===== เครื่อง (7) =====
  ('machine-chest-press', 'Machine Chest Press', 'แมชชีนเชสต์เพรส',
    array['chest press machine'], 'อก', array['ไหล่','แขน'], 'เครื่อง', '⚙️',
    array['ปรับเบาะให้ด้ามจับอยู่ระดับกลางหน้าอก', 'เหมาะฝึกจนใกล้ล้าแบบควบคุมฟอร์มได้ง่าย'], false),
  ('pec-deck-fly', 'Pec Deck Fly', 'เพคเด็คฟลาย',
    array['pec deck', 'butterfly machine', 'บัตเตอร์ฟลาย'], 'อก', array['ไหล่'], 'เครื่อง', '⚙️',
    array['ปรับเบาะให้ด้ามจับอยู่ระดับหน้าอก', 'บีบเข้าหากันช้าๆ ไม่เหวี่ยงเครื่อง'], false),
  ('incline-machine-chest-press', 'Incline Machine Chest Press', 'แมชชีนเชสต์เพรสเอียงขึ้น',
    array['incline machine press'], 'อก', array['ไหล่','แขน'], 'เครื่อง', '⚙️',
    array['เครื่องเอียงขึ้นตายตัว เน้นอกบน', 'ปรับที่นั่งให้ด้ามจับตรงระดับไหล่พอดี'], false),
  ('decline-machine-chest-press', 'Decline Machine Chest Press', 'แมชชีนเชสต์เพรสเอียงลง',
    array['decline machine press'], 'อก', array['ไหล่','แขน'], 'เครื่อง', '⚙️',
    array['เครื่องเอียงลงตายตัว เน้นอกล่าง', 'คุมจังหวะดันออก-กลับช้าๆ'], false),
  ('smith-machine-bench-press', 'Smith Machine Bench Press', 'สมิธแมชชีนเบนช์เพรส',
    array['smith bench press'], 'อก', array['ไหล่','แขน'], 'เครื่อง', '⚙️',
    array['บาร์เคลื่อนที่ในรางตรง ไม่ต้องคุมสมดุลเอง', 'เหมาะฝึกเดี่ยวไม่มีคนช่วยสปอต'], false),
  ('smith-machine-incline-press', 'Smith Machine Incline Press', 'สมิธแมชชีนอินไคลน์เพรส',
    array['smith incline press'], 'อก', array['ไหล่','แขน'], 'เครื่อง', '⚙️',
    array['ตั้งม้านั่งเอียง 30-45 องศาใต้ราง Smith', 'เน้นอกบน ปลอดภัยกว่าบาร์เบลอิสระเมื่อฝึกคนเดียว'], false),
  ('hammer-strength-chest-press', 'Hammer Strength Chest Press', 'แฮมเมอร์สเตรงท์เชสต์เพรส',
    array['plate loaded chest press'], 'อก', array['ไหล่','แขน'], 'เครื่อง', '⚙️',
    array['เครื่องแบบ plate-loaded แขนสองข้างอิสระต่อกัน', 'กันข้างที่แข็งแรงกว่าชดเชยข้างที่อ่อนกว่า'], false),

  -- ===== เคเบิล (6) =====
  ('low-to-high-cable-fly', 'Low-to-High Cable Fly', 'เคเบิลฟลายล่างขึ้นบน',
    array['low to high fly'], 'อก', array['ไหล่'], 'เคเบิล', '🔗',
    array['ตั้งรอกต่ำ ดึงขึ้นมาบรรจบเหนือหน้าอก', 'เน้นอกส่วนบน มุมแรงต่างจากฟลายปกติ'], false),
  ('high-to-low-cable-fly', 'High-to-Low Cable Fly', 'เคเบิลฟลายบนลงล่าง',
    array['high to low fly'], 'อก', array['ไหล่'], 'เคเบิล', '🔗',
    array['ตั้งรอกสูง ดึงลงมาบรรจบใต้หน้าอก', 'เน้นอกส่วนล่าง'], false),
  ('single-arm-cable-crossover', 'Single-Arm Cable Crossover', 'เคเบิลครอสโอเวอร์ข้างเดียว',
    array['single arm crossover'], 'อก', array['แกนกลางลำตัว'], 'เคเบิล', '🔗',
    array['ทำทีละข้าง หันลำตัวเล็กน้อยตามแรงดึง', 'คุมแกนกลางไม่ให้บิดตามน้ำหนัก'], false),
  ('standing-cable-chest-press', 'Standing Cable Chest Press', 'ยืนเคเบิลเชสต์เพรส',
    array['standing cable press'], 'อก', array['แกนกลางลำตัว','ไหล่'], 'เคเบิล', '🔗',
    array['ยืนหันหลังให้รอก ก้าวขาหน้า-หลังเพื่อความมั่นคง', 'ดันออกไปข้างหน้าระดับหน้าอก'], false),
  ('cable-fly-flat', 'Cable Fly (Flat)', 'เคเบิลฟลายระดับกลาง',
    array['mid cable fly', 'flat cable fly'], 'อก', array['ไหล่'], 'เคเบิล', '🔗',
    array['ตั้งรอกสองข้างระดับไหล่', 'กางออก-บีบเข้าเป็นแนวโค้ง ไม่ใช่แนวดัน'], false),
  ('single-arm-cable-fly', 'Single-Arm Cable Fly', 'เคเบิลฟลายข้างเดียว',
    array['single arm fly'], 'อก', array['ไหล่'], 'เคเบิล', '🔗',
    array['ทำทีละข้าง เน้นบีบสุดช่วงเข้าหากึ่งกลางลำตัว', 'ช่วยแก้ข้างที่ไม่สมดุลกัน'], false),

  -- ===== น้ำหนักตัว (8) =====
  ('incline-push-up', 'Incline Push Up', 'อินไคลน์พุชอัพ',
    array['incline push up'], 'อก', array['ไหล่','แขน'], 'น้ำหนักตัว', '🤸',
    array['วางมือบนที่สูง (ม้านั่ง/บาร์) ตัวเอียงขึ้น', 'ผ่อนแรงกว่าพุชอัพพื้นราบ เหมาะมือใหม่'], false),
  ('decline-push-up', 'Decline Push Up', 'เดคลายน์พุชอัพ',
    array['decline push up'], 'อก', array['ไหล่','แขน'], 'น้ำหนักตัว', '🤸',
    array['วางเท้าบนที่สูง มือบนพื้น', 'หนักขึ้นกว่าพุชอัพปกติ เน้นอกบน/ไหล่'], false),
  ('diamond-push-up', 'Diamond Push Up', 'ไดมอนด์พุชอัพ',
    array['triangle push up', 'close grip push up'], 'อก', array['แขน'], 'น้ำหนักตัว', '🤸',
    array['ประกบมือเป็นรูปสามเหลี่ยมใต้อก', 'เน้นแขนส่วนไทรเซ็ปมากกว่าพุชอัพจับกว้าง'], false),
  ('wide-grip-push-up', 'Wide-Grip Push Up', 'พุชอัพจับกว้าง',
    array['wide push up'], 'อก', array['ไหล่'], 'น้ำหนักตัว', '🤸',
    array['วางมือกว้างกว่าไหล่ชัดเจน', 'เน้นอกด้านนอก ลดแรงที่แขน'], false),
  ('archer-push-up', 'Archer Push Up', 'อาร์เชอร์พุชอัพ',
    array['archer push up'], 'อก', array['แขน','แกนกลางลำตัว'], 'น้ำหนักตัว', '🤸',
    array['วางมือกว้าง โยกน้ำหนักตัวไปข้างที่งอศอก อีกข้างเหยียดตรง', 'ระดับยากขึ้น ก่อนไปสู่ one-arm push up'], false),
  ('weighted-dip', 'Weighted Dip', 'ดิปมีน้ำหนักถ่วง',
    array['weighted chest dip'], 'อก', array['ไหล่','แขน'], 'น้ำหนักตัว', '🤸',
    array['ใช้เข็มขัดถ่วงน้ำหนักหรือหนีบดัมเบลระหว่างขา', 'โน้มตัวไปข้างหน้าเล็กน้อยเพื่อเน้นอกมากกว่าแขน'], false),
  ('plyometric-push-up', 'Plyometric Push Up', 'พลัยโอเมตริกพุชอัพ',
    array['clap push up', 'explosive push up'], 'อก', array['ไหล่','แขน'], 'น้ำหนักตัว', '🤸',
    array['ดันตัวขึ้นแรงจนมือลอยพ้นพื้น', 'ฝึกพลังระเบิด ต้องมีพื้นฐานพุชอัพแข็งแรงก่อน'], false),
  ('deficit-push-up', 'Deficit Push Up', 'เดฟิซิตพุชอัพ',
    array['deep push up'], 'อก', array['ไหล่','แขน'], 'น้ำหนักตัว', '🤸',
    array['วางมือบนที่ยกสูง (ดัมเบล/กล่อง) ให้หน้าอกลดต่ำกว่ามือได้', 'เพิ่ม ROM ยืดอกได้ลึกกว่าพุชอัพพื้นราบ'], false)
on conflict (id) do nothing;
