-- 016_exercise_library_seed_back.sql
-- เพิ่มท่ากลุ่ม "หลัง" อีก 35 ท่า (ของเดิมมี 8 ท่าอยู่แล้ว: barbell-row, deadlift, dumbbell-row,
-- face-pull, lat-pulldown, pull-up, seated-cable-row, t-bar-row — เช็คแล้วไม่ชนกับชุดนี้)
-- ครอบคลุม บาร์เบล(6) ดัมเบล(6) เครื่อง(6) เคเบิล(9) น้ำหนักตัว(8)
-- ใส่ highlighter_muscles มาพร้อม insert เลย (ไม่ต้องมี migration update แยกแบบชุดอก)
-- ON CONFLICT (id) DO NOTHING — รันซ้ำได้ปลอดภัย

insert into public.exercise_library
  (id, name, name_th, aliases, primary_muscle, secondary_muscles, equipment, icon, instructions, is_custom, image_url, highlighter_muscles)
values
  -- ===== บาร์เบล (6) =====
  ('pendlay-row', 'Pendlay Row', 'เพนด์เลย์โรว์',
    array['pendlay row'], 'หลัง', array['ไหล่','แขน'], 'บาร์เบล', '🏋️',
    array['วางบาร์ลงพื้นสุดทุกครั้งก่อนเริ่มดึงรอบใหม่ (dead stop)', 'ดึงระเบิดขึ้นแตะช่วงล่างของอก ลำตัวขนานพื้นตลอด'],
    false, null, array['upper-back','lower-back','biceps']),
  ('yates-row', 'Yates Row', 'เยตส์โรว์',
    array['underhand barbell row'], 'หลัง', array['แขน'], 'บาร์เบล', '🏋️',
    array['จับบาร์แบบมือหงาย ลำตัวตั้งชันกว่า bent-over row ปกติ', 'ดึงเข้าหาสะดือ เน้น lats ส่วนล่าง'],
    false, null, array['upper-back','biceps','lower-back']),
  ('rack-pull', 'Rack Pull', 'แร็คพูล',
    array['partial deadlift'], 'หลัง', array['แขน','ขา'], 'บาร์เบล', '🏋️',
    array['วางบาร์บนหมุด Rack เหนือระดับเข่า ลด ROM ลง', 'ยกน้ำหนักได้หนักกว่าเดดลิฟต์เต็ม ROM เน้นล็อกช่วงบน'],
    false, null, array['upper-back','lower-back','trapezius','hamstring']),
  ('deficit-deadlift', 'Deficit Deadlift', 'เดฟิซิตเดดลิฟต์',
    array['deficit deadlift'], 'หลัง', array['ขา'], 'บาร์เบล', '🏋️',
    array['ยืนบนแผ่นยกพื้น/กล่องเตี้ยเพื่อเพิ่ม ROM', 'หนักและยากกว่าเดดลิฟต์ปกติ เน้นจุดดึงตัวขึ้นจากพื้น'],
    false, null, array['lower-back','hamstring','gluteal','trapezius']),
  ('snatch-grip-deadlift', 'Snatch-Grip Deadlift', 'สแนตช์กริปเดดลิฟต์',
    array['wide grip deadlift'], 'หลัง', array['ขา','ไหล่'], 'บาร์เบล', '🏋️',
    array['จับบาร์กว้างมากแบบท่าสแนตช์', 'ลำตัวตั้งชันขึ้น เพิ่มภาระให้หลังบนกว่าจับแคบ'],
    false, null, array['upper-back','lower-back','hamstring','trapezius']),
  ('meadows-row', 'Meadows Row', 'มีโดวส์โรว์',
    array['landmine row'], 'หลัง', array['แขน'], 'บาร์เบล', '🏋️',
    array['ปักปลายบาร์กับมุม/landmine attachment ดึงข้างเดียว', 'มุมดึงเฉียงต่างจาก row ทั่วไป เน้น lats กว้าง'],
    false, null, array['upper-back','biceps']),

  -- ===== ดัมเบล (6) =====
  ('kroc-row', 'Kroc Row', 'คร็อกโรว์',
    array['heavy single arm row'], 'หลัง', array['แขน','แกนกลางลำตัว'], 'ดัมเบล', '💪',
    array['ดึงดัมเบลหนักข้างเดียวแบบยอมให้ลำตัวช่วยเหวี่ยงเล็กน้อย', 'เน้นจำนวนครั้งสูง ไม่ใช่ฟอร์มสวยแบบ strict row'],
    false, null, array['upper-back','biceps','forearm']),
  ('chest-supported-dumbbell-row', 'Chest-Supported Dumbbell Row', 'เชสต์ซัพพอร์ตดัมเบลโรว์',
    array['incline bench row'], 'หลัง', array['แขน'], 'ดัมเบล', '💪',
    array['นอนคว่ำบนม้านั่งเอียง อกแนบเบาะตลอด', 'ตัดแรงเหวี่ยงจากหลังล่าง เน้นกล้ามหลังล้วนๆ'],
    false, null, array['upper-back','biceps']),
  ('renegade-row', 'Renegade Row', 'เรเนเกดโรว์',
    array['plank row'], 'หลัง', array['แกนกลางลำตัว','ไหล่'], 'ดัมเบล', '💪',
    array['อยู่ในท่าแพลงก์มือถือดัมเบล ดึงสลับข้าง', 'คุมสะโพกไม่ให้บิดตามจังหวะดึง'],
    false, null, array['upper-back','abs','biceps']),
  ('dumbbell-high-pull', 'Dumbbell High Pull', 'ดัมเบลไฮพูล',
    array['db high pull'], 'หลัง', array['ไหล่'], 'ดัมเบล', '💪',
    array['ดึงดัมเบลขึ้นเร็วจากหน้าขาถึงระดับไหล่ ศอกนำ', 'เน้น trapezius และหลังบน เคลื่อนไหวแบบ explosive'],
    false, null, array['trapezius','upper-back']),
  ('dumbbell-deadlift', 'Dumbbell Deadlift', 'ดัมเบลเดดลิฟต์',
    array['db deadlift'], 'หลัง', array['ขา'], 'ดัมเบล', '💪',
    array['ถือดัมเบลข้างลำตัวแทนบาร์เบล', 'เหมาะมือใหม่ฝึกแพทเทิร์นฮินจ์ก่อนขยับไปบาร์เบล'],
    false, null, array['lower-back','hamstring','gluteal']),
  ('dumbbell-shrug', 'Dumbbell Shrug', 'ดัมเบลชรัก',
    array['shrug'], 'หลัง', array['แขน'], 'ดัมเบล', '💪',
    array['ยกไหล่ขึ้นตรงๆ ไม่หมุนไหล่', 'ค้างบนสุด 1 วิ ก่อนปล่อยลงช้าๆ'],
    false, null, array['trapezius','forearm']),

  -- ===== เครื่อง (6) =====
  ('assisted-pull-up-machine', 'Assisted Pull-Up Machine', 'แมชชีนช่วยดึงข้อ',
    array['assisted pull up'], 'หลัง', array['แขน'], 'เครื่อง', '⚙️',
    array['ปรับน้ำหนักถ่วงช่วยตามระดับความแข็งแรง', 'เหมาะฝึกก่อนทำ pull-up ด้วยน้ำหนักตัวเต็มๆ'],
    false, null, array['upper-back','biceps']),
  ('plate-loaded-row-machine', 'Plate-Loaded Row Machine', 'แมชชีนโรว์แบบใส่แผ่นน้ำหนัก',
    array['hammer strength row'], 'หลัง', array['แขน'], 'เครื่อง', '⚙️',
    array['นั่งอกแนบเบาะพยุง ดึงด้ามจับเข้าหาลำตัว', 'แขนสองข้างอิสระต่อกัน กันข้างที่แข็งแรงชดเชยข้างอ่อน'],
    false, null, array['upper-back','biceps']),
  ('smith-machine-bent-over-row', 'Smith Machine Bent-Over Row', 'สมิธแมชชีนเบนท์โอเวอร์โรว์',
    array['smith machine row'], 'หลัง', array['แขน'], 'เครื่อง', '⚙️',
    array['ก้มตัวจับบาร์ในราง Smith ดึงเข้าหาลำตัว', 'บาร์เคลื่อนในรางตรง ควบคุมง่ายกว่าบาร์เบลอิสระ'],
    false, null, array['upper-back','lower-back','biceps']),
  ('reverse-pec-deck-row', 'Reverse Pec Deck', 'รีเวิร์สเพคเด็ค',
    array['rear delt machine'], 'หลัง', array['ไหล่'], 'เครื่อง', '⚙️',
    array['หันหน้าเข้าเครื่อง กางแขนออกด้านหลัง', 'เน้นไหล่หลังและกล้ามหลังบนช่วงกลาง'],
    false, null, array['back-deltoids','upper-back']),
  ('back-extension-machine', 'Back Extension Machine', 'แมชชีนแบ็คเอ็กซ์เทนชัน',
    array['hyperextension machine'], 'หลัง', array['ขา'], 'เครื่อง', '⚙️',
    array['วางสะโพกบนเบาะ ก้มตัวลง-เงยขึ้นควบคุมจังหวะ', 'เน้นหลังล่างและสะโพก เพิ่มน้ำหนักถ่วงได้เมื่อแข็งแรงขึ้น'],
    false, null, array['lower-back','gluteal','hamstring']),
  ('lat-pulldown-machine', 'Plate-Loaded Lat Pulldown', 'แมชชีนแลตพูลดาวน์แบบใส่แผ่น',
    array['lat pulldown machine'], 'หลัง', array['แขน'], 'เครื่อง', '⚙️',
    array['นั่งดึงด้ามจับลงมาที่ระดับอกบน', 'ทางเลือกแทนแบบเคเบิล ให้ความรู้สึกมั่นคงกว่า'],
    false, null, array['upper-back','biceps']),

  -- ===== เคเบิล (9) =====
  ('straight-arm-pulldown', 'Straight-Arm Pulldown', 'สเตรทอาร์มพูลดาวน์',
    array['straight arm pushdown'], 'หลัง', array['ไหล่'], 'เคเบิล', '🔗',
    array['ยืนหน้ารอกสูง แขนตรงตลอด ดึงบาร์ลงมาที่ต้นขา', 'แยก lats ออกจากแขน ไม่ใช้ข้อศอกช่วยดึง'],
    false, null, array['upper-back','back-deltoids']),
  ('single-arm-lat-pulldown', 'Single-Arm Lat Pulldown', 'แลตพูลดาวน์ข้างเดียว',
    array['single arm pulldown'], 'หลัง', array['แขน'], 'เคเบิล', '🔗',
    array['เปลี่ยนด้ามจับเป็นแบบเดี่ยว ดึงทีละข้าง', 'แก้ปัญหาข้างที่ไม่สมดุลกันได้ดี'],
    false, null, array['upper-back','biceps']),
  ('close-grip-seated-row', 'Close-Grip Seated Cable Row', 'ซีทเค็บเบิลโรว์จับแคบ',
    array['v grip row'], 'หลัง', array['แขน'], 'เคเบิล', '🔗',
    array['ใช้ด้ามจับรูปตัว V มือหันเข้าหากัน', 'ดึงเข้าหาสะดือ เน้นความหนาของหลังกลาง'],
    false, null, array['upper-back','biceps']),
  ('wide-grip-seated-row', 'Wide-Grip Seated Cable Row', 'ซีทเค็บเบิลโรว์จับกว้าง',
    array['wide row'], 'หลัง', array['ไหล่'], 'เคเบิล', '🔗',
    array['ใช้บาร์ตรงจับกว้างกว่าไหล่', 'เน้นหลังบนและกล้ามรอบสะบัก'],
    false, null, array['upper-back','back-deltoids']),
  ('single-arm-cable-row', 'Single-Arm Cable Row', 'เคเบิลโรว์ข้างเดียว',
    array['single arm row'], 'หลัง', array['แกนกลางลำตัว','แขน'], 'เคเบิล', '🔗',
    array['ดึงทีละข้าง อีกข้างวางมือพยุงหรือปล่อยข้างลำตัว', 'คุมลำตัวไม่ให้บิดตามแรงดึง'],
    false, null, array['upper-back','obliques','biceps']),
  ('cable-pullover', 'Cable Pullover', 'เคเบิลพูลโอเวอร์',
    array['cable pullover'], 'หลัง', array['อก'], 'เคเบิล', '🔗',
    array['ตั้งรอกสูง แขนตรงดึงลงมาถึงต้นขา', 'แรงตึงคงที่ตลอดช่วงการเคลื่อนไหว ต่างจากดัมเบลพูลโอเวอร์'],
    false, null, array['upper-back','chest']),
  ('reverse-grip-lat-pulldown', 'Reverse-Grip Lat Pulldown', 'แลตพูลดาวน์จับหงาย',
    array['underhand pulldown'], 'หลัง', array['แขน'], 'เคเบิล', '🔗',
    array['จับบาร์แบบมือหงายแคบกว่าจับคว่ำปกติ', 'เน้น lats ส่วนล่างและไบเซ็ปมากขึ้น'],
    false, null, array['upper-back','biceps']),
  ('cable-shrug', 'Cable Shrug', 'เคเบิลชรัก',
    array['cable shrug'], 'หลัง', array['แขน'], 'เคเบิล', '🔗',
    array['ยืนหน้ารอกต่ำ ยกไหล่ขึ้นตรงๆ', 'แรงตึงจากเคเบิลคงที่กว่าดัมเบล/บาร์เบล'],
    false, null, array['trapezius','forearm']),
  ('high-cable-row', 'High Cable Row', 'ไฮเคเบิลโรว์',
    array['high pulley row'], 'หลัง', array['ไหล่'], 'เคเบิล', '🔗',
    array['ตั้งรอกสูงกว่าระดับไหล่ ดึงเข้าหาหน้าอกบน', 'มุมดึงจากบนลงล่าง เน้นหลังบนและไหล่หลัง'],
    false, null, array['back-deltoids','upper-back','trapezius']),

  -- ===== น้ำหนักตัว (8) =====
  ('chin-up', 'Chin-Up', 'ชินอัพ',
    array['chin up', 'underhand pull up'], 'หลัง', array['แขน'], 'น้ำหนักตัว', '🤸',
    array['จับบาร์แบบมือหงาย แคบกว่า pull-up', 'ใช้ไบเซ็ปช่วยดึงมากกว่า pull-up จับคว่ำ'],
    false, null, array['upper-back','biceps']),
  ('inverted-row', 'Inverted Row', 'อินเวอร์เต็ดโรว์',
    array['bodyweight row', 'australian pull up'], 'หลัง', array['แขน'], 'น้ำหนักตัว', '🤸',
    array['นอนใต้บาร์ต่ำ ลำตัวตรงเป็นเส้นเดียว ดึงอกขึ้นแตะบาร์', 'ปรับความยากด้วยการยกเท้าสูง/ต่ำ'],
    false, null, array['upper-back','biceps']),
  ('wide-grip-pull-up', 'Wide-Grip Pull-Up', 'พูลอัพจับกว้าง',
    array['wide pull up'], 'หลัง', array['ไหล่'], 'น้ำหนักตัว', '🤸',
    array['จับบาร์กว้างกว่าไหล่ชัดเจน', 'เน้นความกว้างของ lats มากกว่าจับแคบ'],
    false, null, array['upper-back','back-deltoids']),
  ('neutral-grip-pull-up', 'Neutral-Grip Pull-Up', 'พูลอัพจับคว่ำขนาน',
    array['hammer grip pull up'], 'หลัง', array['แขน'], 'น้ำหนักตัว', '🤸',
    array['จับด้ามคู่ขนานฝ่ามือหันเข้าหากัน', 'ลดแรงกดข้อมือ/ไหล่กว่าจับคว่ำหรือหงายสุด'],
    false, null, array['upper-back','biceps','forearm']),
  ('muscle-up', 'Muscle-Up', 'มัสเซิลอัพ',
    array['muscle up'], 'หลัง', array['อก','แขน'], 'น้ำหนักตัว', '🤸',
    array['ดึงข้อขึ้นสุดแล้วหมุนข้อมือดันตัวขึ้นเหนือบาร์', 'ต้องมีพื้นฐาน pull-up และ dip ที่แข็งแรงมากก่อนฝึก'],
    false, null, array['upper-back','chest','triceps']),
  ('superman', 'Superman', 'ซุปเปอร์แมน',
    array['superman hold'], 'หลัง', array['ขา'], 'น้ำหนักตัว', '🤸',
    array['นอนคว่ำ ยกแขน-ขาขึ้นพร้อมกันจนลำตัวโค้ง', 'ค้างไว้สั้นๆ แล้วปล่อยลงช้าๆ เน้นหลังล่าง'],
    false, null, array['lower-back','gluteal']),
  ('bird-dog', 'Bird Dog', 'เบิร์ดด็อก',
    array['bird dog'], 'หลัง', array['แกนกลางลำตัว','ขา'], 'น้ำหนักตัว', '🤸',
    array['คุกเข่า-มือยันพื้น ยื่นแขนและขาตรงข้ามออกพร้อมกัน', 'คุมสะโพกไม่ให้บิด เน้นความมั่นคงของแกนกลาง/หลังล่าง'],
    false, null, array['lower-back','abs','gluteal']),
  ('scapular-pull-up', 'Scapular Pull-Up', 'สแคปพูลาร์พูลอัพ',
    array['scap pull up'], 'หลัง', array['ไหล่'], 'น้ำหนักตัว', '🤸',
    array['ห้อยตัวที่บาร์ แขนตรง ยกตัวขึ้นเล็กน้อยด้วยการหุบสะบักเท่านั้น', 'ไม่งอศอก เป็นท่าเตรียมความพร้อมก่อนฝึก pull-up'],
    false, null, array['upper-back','trapezius'])
on conflict (id) do nothing;
