-- 017_exercise_library_seed_legs.sql
-- เพิ่มท่ากลุ่ม "ขา" อีก 35 ท่า (ของเดิมมี 10 ท่าอยู่แล้ว: bulgarian-split-squat, calf-raise,
-- front-squat, hip-thrust, leg-curl, leg-extension, leg-press, romanian-deadlift, squat,
-- walking-lunge — เช็คแล้วไม่ชนกับชุดนี้)
-- ครอบคลุม บาร์เบล(7) ดัมเบล(7) เครื่อง(7) เคเบิล(5) น้ำหนักตัว/คีทเทิลเบล(9)
-- ON CONFLICT (id) DO NOTHING — รันซ้ำได้ปลอดภัย

insert into public.exercise_library
  (id, name, name_th, aliases, primary_muscle, secondary_muscles, equipment, icon, instructions, is_custom, image_url, highlighter_muscles)
values
  -- ===== บาร์เบล (7) =====
  ('box-squat', 'Box Squat', 'บ๊อกซ์สควอท',
    array['box squat'], 'ขา', array['แกนกลางลำตัว'], 'บาร์เบล', '🏋️',
    array['นั่งแตะกล่อง/ม้านั่งเตี้ยแล้วยืนขึ้นทันที ไม่ผ่อนน้ำหนักค้างบนกล่อง', 'ช่วยฝึกจังหวะเริ่มออกแรงจากจุดหยุดนิ่ง'],
    false, null, array['quadriceps','gluteal','hamstring']),
  ('zercher-squat', 'Zercher Squat', 'เซอร์เชอร์สควอท',
    array['zercher squat'], 'ขา', array['แกนกลางลำตัว','แขน'], 'บาร์เบล', '🏋️',
    array['อุ้มบาร์ไว้ในข้อพับแขนหน้าท้อง', 'เน้นแกนกลางและหลังบนทำงานหนักกว่าสควอทแบกบ่า'],
    false, null, array['quadriceps','gluteal','abs']),
  ('sumo-deadlift', 'Sumo Deadlift', 'ซูโม่เดดลิฟต์',
    array['sumo deadlift'], 'ขา', array['หลัง'], 'บาร์เบล', '🏋️',
    array['ยืนขากว้าง ปลายเท้าชี้ออก จับบาร์แคบระหว่างขา', 'เน้นต้นขาด้านในและสะโพกมากกว่าเดดลิฟต์ปกติ'],
    false, null, array['adductor','quadriceps','gluteal','lower-back']),
  ('barbell-lunge', 'Barbell Lunge', 'บาร์เบลลันจ์',
    array['barbell lunge'], 'ขา', array['หลัง'], 'บาร์เบล', '🏋️',
    array['แบกบาร์บนบ่า ก้าวขาลันจ์สลับข้าง', 'คุมสมดุลด้วยแกนกลางตลอดจังหวะ'],
    false, null, array['quadriceps','gluteal','hamstring']),
  ('overhead-squat', 'Overhead Squat', 'โอเวอร์เฮดสควอท',
    array['overhead squat'], 'ขา', array['ไหล่','แกนกลางลำตัว'], 'บาร์เบล', '🏋️',
    array['ยกบาร์เหนือศีรษะแขนล็อกตลอดการสควอท', 'ต้องการความยืดหยุ่นไหล่/สะโพกสูง เริ่มด้วยน้ำหนักเบา'],
    false, null, array['quadriceps','gluteal','front-deltoids']),
  ('good-morning', 'Good Morning', 'กู๊ดมอร์นิ่ง',
    array['good morning'], 'ขา', array['หลัง'], 'บาร์เบล', '🏋️',
    array['แบกบาร์บนบ่า ก้มสะโพกไปข้างหน้าขาเกือบตรง', 'รู้สึกยืดที่ต้นขาหลังและหลังล่าง'],
    false, null, array['hamstring','lower-back','gluteal']),
  ('barbell-step-up', 'Barbell Step-Up', 'บาร์เบลสเต็ปอัพ',
    array['barbell step up'], 'ขา', array['หลัง'], 'บาร์เบล', '🏋️',
    array['แบกบาร์บนบ่า ก้าวขึ้นกล่อง/ม้านั่งทีละข้าง', 'คุมจังหวะลงช้าๆ ไม่กระแทกเข่า'],
    false, null, array['quadriceps','gluteal']),

  -- ===== ดัมเบล (7) =====
  ('goblet-squat', 'Goblet Squat', 'กอบเล็ตสควอท',
    array['goblet squat'], 'ขา', array['แกนกลางลำตัว'], 'ดัมเบล', '💪',
    array['ถือดัมเบลแนบอกด้วยสองมือ สควอทลงระหว่างขา', 'ท่าเริ่มต้นที่ดีสำหรับฝึกฟอร์มสควอท'],
    false, null, array['quadriceps','gluteal']),
  ('dumbbell-lunge', 'Dumbbell Lunge', 'ดัมเบลลันจ์',
    array['dumbbell lunge'], 'ขา', array['หลัง'], 'ดัมเบล', '💪',
    array['ถือดัมเบลข้างลำตัว ก้าวลันจ์สลับข้าง', 'เข่าหลังแตะพื้นเบาๆ ไม่กระแทก'],
    false, null, array['quadriceps','gluteal','hamstring']),
  ('dumbbell-step-up', 'Dumbbell Step-Up', 'ดัมเบลสเต็ปอัพ',
    array['dumbbell step up'], 'ขา', array['หลัง'], 'ดัมเบล', '💪',
    array['ถือดัมเบลข้างลำตัว ก้าวขึ้นกล่อง', 'ดันผ่านส้นเท้าขาที่อยู่บนกล่อง'],
    false, null, array['quadriceps','gluteal']),
  ('dumbbell-sumo-squat', 'Dumbbell Sumo Squat', 'ดัมเบลซูโม่สควอท',
    array['dumbbell sumo squat'], 'ขา', array['หลัง'], 'ดัมเบล', '💪',
    array['ถือดัมเบลตั้งด้วยสองมือระหว่างขา ยืนขากว้าง', 'เน้นต้นขาด้านในและสะโพก'],
    false, null, array['adductor','quadriceps','gluteal']),
  ('single-leg-romanian-deadlift', 'Single-Leg Romanian Deadlift', 'โรมาเนียนเดดลิฟต์ขาเดียว',
    array['single leg rdl'], 'ขา', array['แกนกลางลำตัว'], 'ดัมเบล', '💪',
    array['ยืนขาเดียวถือดัมเบล ก้มตัวยกขาหลังขึ้นให้ลำตัวขนานพื้น', 'ฝึกสมดุลไปพร้อมความแข็งแรงของหลังต้นขา'],
    false, null, array['hamstring','gluteal','abs']),
  ('dumbbell-calf-raise', 'Dumbbell Calf Raise', 'ดัมเบลคาล์ฟเรส',
    array['dumbbell calf raise'], 'ขา', array[]::text[], 'ดัมเบล', '💪',
    array['ถือดัมเบลยืนปลายเท้าบนขอบพื้นต่าง', 'เขย่งขึ้นสุดค้าง 1 วิ ก่อนปล่อยลงช้าๆ'],
    false, null, array['calves']),
  ('curtsy-lunge', 'Curtsy Lunge', 'เคอร์ทซี่ลันจ์',
    array['curtsy lunge'], 'ขา', array[]::text[], 'ดัมเบล', '💪',
    array['ก้าวขาไขว้ไปด้านหลังทแยงคล้ายท่าคำนับ', 'เน้นกล้ามสะโพกด้านข้างและก้น'],
    false, null, array['gluteal','quadriceps','adductor']),

  -- ===== เครื่อง (7) =====
  ('hack-squat', 'Hack Squat', 'แฮ็คสควอท',
    array['hack squat machine'], 'ขา', array[]::text[], 'เครื่อง', '⚙️',
    array['พิงหลังกับเครื่องมุมเอียง ดันแผ่นขึ้น-ลง', 'ปลอดภัยกว่าบาร์เบลสควอทเมื่อฝึกคนเดียว'],
    false, null, array['quadriceps','gluteal']),
  ('seated-leg-curl', 'Seated Leg Curl', 'ซีทเลกเคิร์ล',
    array['seated leg curl'], 'ขา', array[]::text[], 'เครื่อง', '⚙️',
    array['นั่งงอเข่าดึงแผ่นรองลงมาใต้เข่า', 'แยกกล้ามหลังต้นขาชัดกว่าท่านอนคว่ำ'],
    false, null, array['hamstring']),
  ('lying-leg-curl', 'Lying Leg Curl', 'ไลอิ้งเลกเคิร์ล',
    array['lying leg curl'], 'ขา', array[]::text[], 'เครื่อง', '⚙️',
    array['นอนคว่ำงอเข่าดึงแผ่นรองขึ้นหาก้น', 'คุมจังหวะปล่อยลงช้าๆ ไม่ปล่อยตกอิสระ'],
    false, null, array['hamstring']),
  ('smith-machine-squat', 'Smith Machine Squat', 'สมิธแมชชีนสควอท',
    array['smith machine squat'], 'ขา', array['แกนกลางลำตัว'], 'เครื่อง', '⚙️',
    array['บาร์เคลื่อนที่ในรางตรง ไม่ต้องคุมสมดุลเอง', 'เหมาะฝึกคนเดียวไม่มีคนสปอต'],
    false, null, array['quadriceps','gluteal']),
  ('standing-calf-raise-machine', 'Standing Calf Raise Machine', 'แมชชีนยืนคาล์ฟเรส',
    array['standing calf raise'], 'ขา', array[]::text[], 'เครื่อง', '⚙️',
    array['สอดไหล่ใต้เบาะรองยืนเขย่งปลายเท้า', 'เน้นกล้ามน่องล้วนๆ'],
    false, null, array['calves']),
  ('hip-abduction-machine', 'Hip Abduction Machine', 'แมชชีนฮิปแอบดักชัน',
    array['hip abduction machine'], 'ขา', array[]::text[], 'เครื่อง', '⚙️',
    array['นั่งกางขาออกด้านนอกต้านแรงเครื่อง', 'เน้นกล้ามสะโพกด้านนอก'],
    false, null, array['abductors']),
  ('hip-adduction-machine', 'Hip Adduction Machine', 'แมชชีนฮิปแอดดักชัน',
    array['hip adduction machine'], 'ขา', array[]::text[], 'เครื่อง', '⚙️',
    array['นั่งหุบขาเข้าหากันต้านแรงเครื่อง', 'เน้นกล้ามต้นขาด้านใน'],
    false, null, array['adductor']),

  -- ===== เคเบิล (5) =====
  ('cable-pull-through', 'Cable Pull-Through', 'เคเบิลพูลทรู',
    array['cable pull through'], 'ขา', array['หลัง'], 'เคเบิล', '🔗',
    array['หันหลังให้รอกต่ำ ก้มสะโพกดึงเชือกผ่านระหว่างขา', 'แพทเทิร์นฮินจ์ที่ปลอดภัยสำหรับฝึกหลังล่าง/สะโพก'],
    false, null, array['hamstring','gluteal','lower-back']),
  ('cable-squat', 'Cable Squat', 'เคเบิลสควอท',
    array['cable squat'], 'ขา', array[]::text[], 'เคเบิล', '🔗',
    array['ยืนหันหน้าเข้ารอกต่ำถือด้ามจับแนบอก สควอทลง', 'แรงตึงคงที่ตลอดจังหวะ'],
    false, null, array['quadriceps','gluteal']),
  ('cable-kickback', 'Cable Kickback', 'เคเบิลคิกแบ็ค',
    array['cable kickback'], 'ขา', array[]::text[], 'เคเบิล', '🔗',
    array['ผูกสายที่ข้อเท้า เตะขาไปด้านหลัง', 'เน้นกล้ามก้นล้วนๆ'],
    false, null, array['gluteal']),
  ('cable-hip-abduction', 'Cable Hip Abduction', 'เคเบิลฮิปแอบดักชัน',
    array['cable hip abduction'], 'ขา', array[]::text[], 'เคเบิล', '🔗',
    array['ผูกสายที่ข้อเท้า กางขาออกด้านข้าง', 'ยืนพยุงตัวให้มั่นคงตลอดเซ็ต'],
    false, null, array['abductors']),
  ('cable-romanian-deadlift', 'Cable Romanian Deadlift', 'เคเบิลโรมาเนียนเดดลิฟต์',
    array['cable rdl'], 'ขา', array['หลัง'], 'เคเบิล', '🔗',
    array['ถือด้ามจับรอกต่ำ ก้มสะโพกไปข้างหลังขาเกือบตรง', 'แรงตึงคงที่กว่าดัมเบล/บาร์เบล'],
    false, null, array['hamstring','gluteal','lower-back']),

  -- ===== น้ำหนักตัว/คีทเทิลเบล (9) =====
  ('pistol-squat', 'Pistol Squat', 'พิสตอลสควอท',
    array['pistol squat'], 'ขา', array['แกนกลางลำตัว'], 'น้ำหนักตัว', '🤸',
    array['สควอทขาเดียว อีกขาเหยียดตรงไปข้างหน้า', 'ต้องการความแข็งแรงและสมดุลสูงมาก'],
    false, null, array['quadriceps','gluteal','abs']),
  ('jump-squat', 'Jump Squat', 'จั๊มพ์สควอท',
    array['jump squat'], 'ขา', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['สควอทลงแล้วกระโดดขึ้นสุดแรง ลงเข่างอรับแรงกระแทก', 'ฝึกพลังระเบิดของขาและก้น'],
    false, null, array['quadriceps','gluteal','calves']),
  ('box-jump', 'Box Jump', 'บ๊อกซ์จั๊มพ์',
    array['box jump'], 'ขา', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['กระโดดขึ้นกล่องด้วยสองขาพร้อมกัน ลงเบาๆ ด้วยปลายเท้า', 'เลือกความสูงกล่องให้เหมาะกับระดับความสามารถ'],
    false, null, array['quadriceps','gluteal','calves']),
  ('wall-sit', 'Wall Sit', 'วอลล์ซิท',
    array['wall sit'], 'ขา', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['พิงหลังกับกำแพง งอเข่า 90 องศาค้างไว้', 'ฝึกความอึดของกล้ามต้นขาหน้า'],
    false, null, array['quadriceps']),
  ('glute-bridge', 'Glute Bridge', 'กลูทบริดจ์',
    array['glute bridge'], 'ขา', array['แกนกลางลำตัว'], 'น้ำหนักตัว', '🤸',
    array['นอนหงายชันเข่า ยกสะโพกขึ้นบีบก้นค้าง', 'พื้นฐานก่อนไปฝึก hip thrust ที่หนักขึ้น'],
    false, null, array['gluteal','hamstring','abs']),
  ('single-leg-glute-bridge', 'Single-Leg Glute Bridge', 'กลูทบริดจ์ขาเดียว',
    array['single leg glute bridge'], 'ขา', array['แกนกลางลำตัว'], 'น้ำหนักตัว', '🤸',
    array['ยกสะโพกด้วยขาเดียว อีกขาเหยียดลอย', 'เพิ่มความยากและช่วยแก้ข้างที่ไม่สมดุลกัน'],
    false, null, array['gluteal','hamstring','abs']),
  ('step-up-bodyweight', 'Bodyweight Step-Up', 'สเต็ปอัพน้ำหนักตัว',
    array['step up'], 'ขา', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['ก้าวขึ้นกล่อง/บันไดด้วยขาเดียว ไม่ใช้แรงเหวี่ยงจากขาล่าง', 'เหมาะวอร์มอัพหรือฝึกความสมดุล'],
    false, null, array['quadriceps','gluteal']),
  ('nordic-hamstring-curl', 'Nordic Hamstring Curl', 'นอร์ดิกแฮมสตริงเคิร์ล',
    array['nordic curl'], 'ขา', array['แกนกลางลำตัว'], 'น้ำหนักตัว', '🤸',
    array['คุกเข่าให้คนช่วยกดยึดข้อเท้า โน้มตัวลงข้างหน้าช้าๆ คุมด้วยหลังต้นขา', 'ท่ายากมาก เริ่มจาก ROM สั้นก่อน'],
    false, null, array['hamstring']),
  ('kettlebell-goblet-squat', 'Kettlebell Goblet Squat', 'กอบเล็ตสควอทเคทเทิลเบล',
    array['kettlebell goblet squat'], 'ขา', array['แกนกลางลำตัว'], 'คีทเทิลเบล', '🔔',
    array['ถือเคทเทิลเบลแนบอกด้วยสองมือ สควอทลงระหว่างขา', 'จับด้ามแนวตั้งทำให้สมดุลง่ายกว่าดัมเบล'],
    false, null, array['quadriceps','gluteal'])
on conflict (id) do nothing;
