-- 018_exercise_library_seed_shoulders.sql
-- เพิ่มท่ากลุ่ม "ไหล่" อีก 28 ท่า (ของเดิมมี 7 ท่าอยู่แล้ว: arnold-press, dumbbell-shoulder-press,
-- front-raise, lateral-raise, rear-delt-fly, shoulder-press, upright-row — เช็คแล้วไม่ชนกับชุดนี้)
-- ครอบคลุม บาร์เบล(5) ดัมเบล(6) เครื่อง(5) เคเบิล(7) น้ำหนักตัว(5)
-- ON CONFLICT (id) DO NOTHING — รันซ้ำได้ปลอดภัย

insert into public.exercise_library
  (id, name, name_th, aliases, primary_muscle, secondary_muscles, equipment, icon, instructions, is_custom, image_url, highlighter_muscles)
values
  -- ===== บาร์เบล (5) =====
  ('military-press', 'Military Press', 'มิลิทารีเพรส',
    array['strict press'], 'ไหล่', array['แขน'], 'บาร์เบล', '🏋️',
    array['ยืนตรงขาชิด ดันบาร์ขึ้นเหนือศีรษะจนแขนล็อก', 'เข้มงวดกว่า push press เพราะห้ามใช้แรงเหวี่ยงจากขา'],
    false, null, array['front-deltoids','triceps']),
  ('push-press', 'Push Press', 'พุชเพรส',
    array['push press'], 'ไหล่', array['ขา','แขน'], 'บาร์เบล', '🏋️',
    array['ย่อเข่าเล็กน้อยแล้วเหยียดขาช่วยส่งแรงดันบาร์ขึ้น', 'ยกน้ำหนักได้มากกว่า strict press เพราะมีแรงช่วยจากขา'],
    false, null, array['front-deltoids','triceps','quadriceps']),
  ('behind-the-neck-press', 'Behind-the-Neck Press', 'เพรสหลังคอ',
    array['behind neck press'], 'ไหล่', array['แขน'], 'บาร์เบล', '🏋️',
    array['ดันบาร์จากด้านหลังคอขึ้นเหนือศีรษะ', 'ต้องการความยืดหยุ่นไหล่สูง ระวังถ้าไหล่ไม่ยืดหยุ่นพอ'],
    false, null, array['front-deltoids','back-deltoids','triceps']),
  ('barbell-front-raise', 'Barbell Front Raise', 'บาร์เบลฟรอนต์เรส',
    array['barbell front raise'], 'ไหล่', array[]::text[], 'บาร์เบล', '🏋️',
    array['จับบาร์สองมือยกขึ้นตรงหน้าระดับไหล่', 'ไม่แกว่งลำตัวช่วยส่งแรง'],
    false, null, array['front-deltoids']),
  ('landmine-press', 'Landmine Press', 'แลนด์ไมน์เพรส',
    array['landmine press'], 'ไหล่', array['แกนกลางลำตัว','แขน'], 'บาร์เบล', '🏋️',
    array['ปักปลายบาร์กับมุม/landmine attachment ดันขึ้นทแยงข้างเดียว', 'มุมดันโค้งช่วยลดแรงกดข้อไหล่กว่าดันตรงขึ้น'],
    false, null, array['front-deltoids','triceps','abs']),

  -- ===== ดัมเบล (6) =====
  ('seated-dumbbell-press', 'Seated Dumbbell Press', 'ซีทดัมเบลเพรส',
    array['seated db press'], 'ไหล่', array['แขน'], 'ดัมเบล', '💪',
    array['นั่งพิงพนักดันดัมเบลขึ้นเหนือศีรษะ', 'ตัดแรงเหวี่ยงจากขา ต่างจากยืนดัน'],
    false, null, array['front-deltoids','triceps']),
  ('single-arm-dumbbell-press', 'Single-Arm Dumbbell Press', 'ดัมเบลเพรสข้างเดียว',
    array['single arm db press'], 'ไหล่', array['แกนกลางลำตัว','แขน'], 'ดัมเบล', '💪',
    array['ดันทีละข้าง อีกข้างล็อกลำตัวไม่ให้บิด', 'ฝึกความมั่นคงของแกนกลางไปพร้อมไหล่'],
    false, null, array['front-deltoids','triceps','abs']),
  ('leaning-lateral-raise', 'Leaning Lateral Raise', 'ลีนนิ่งแลเทอรัลเรส',
    array['leaning lateral raise'], 'ไหล่', array[]::text[], 'ดัมเบล', '💪',
    array['เอนตัวพิงเสา/ราวจับ ยกดัมเบลข้างเดียวออกด้านข้าง', 'เอียงตัวช่วยเพิ่ม ROM ที่จุดเริ่มต้นของการยก'],
    false, null, array['front-deltoids']),
  ('incline-rear-delt-raise', 'Incline Rear Delt Raise', 'อินไคลน์เรียร์เดลต์เรส',
    array['incline rear delt raise'], 'ไหล่', array[]::text[], 'ดัมเบล', '💪',
    array['นอนคว่ำบนม้านั่งเอียง กางแขนออกด้านหลัง', 'พยุงลำตัวนิ่งกว่าท่าก้มยืน ลดแรงเหวี่ยงจากหลัง'],
    false, null, array['back-deltoids']),
  ('cuban-press', 'Cuban Press', 'คิวบันเพรส',
    array['cuban press'], 'ไหล่', array['แขน'], 'ดัมเบล', '💪',
    array['ยกศอกระดับไหล่ หมุนแขนขึ้นก่อนดันเพรสต่อ', 'ท่าผสมช่วยสุขภาพไหล่และกล้ามหมุนไหล่'],
    false, null, array['front-deltoids','back-deltoids']),
  ('plate-front-raise', 'Plate Front Raise', 'เพลทฟรอนต์เรส',
    array['plate raise'], 'ไหล่', array[]::text[], 'ดัมเบล', '💪',
    array['จับแผ่นน้ำหนักสองมือยกขึ้นตรงหน้า', 'ทำได้โดยไม่ต้องมีดัมเบลคู่ ใช้แผ่นเดียวก็พอ'],
    false, null, array['front-deltoids']),

  -- ===== เครื่อง (5) =====
  ('machine-shoulder-press', 'Machine Shoulder Press', 'แมชชีนโชลเดอร์เพรส',
    array['shoulder press machine'], 'ไหล่', array['แขน'], 'เครื่อง', '⚙️',
    array['นั่งดันด้ามจับขึ้นเหนือศีรษะ', 'ปรับเบาะให้ด้ามจับอยู่ระดับไหล่พอดีก่อนเริ่ม'],
    false, null, array['front-deltoids','triceps']),
  ('machine-lateral-raise', 'Machine Lateral Raise', 'แมชชีนแลเทอรัลเรส',
    array['lateral raise machine'], 'ไหล่', array[]::text[], 'เครื่อง', '⚙️',
    array['นั่งด้านข้างเครื่อง ยกแขนออกด้านข้างต้านแรงเครื่อง', 'คุมฟอร์มง่ายกว่าดัมเบลเพราะแรงต้านคงที่'],
    false, null, array['front-deltoids']),
  ('smith-machine-shoulder-press', 'Smith Machine Shoulder Press', 'สมิธแมชชีนโชลเดอร์เพรส',
    array['smith shoulder press'], 'ไหล่', array['แขน'], 'เครื่อง', '⚙️',
    array['บาร์เคลื่อนที่ในรางตรงเหนือศีรษะ', 'เหมาะฝึกคนเดียวไม่มีคนสปอต'],
    false, null, array['front-deltoids','triceps']),
  ('plate-loaded-shoulder-press', 'Plate-Loaded Shoulder Press', 'แมชชีนโชลเดอร์เพรสแบบใส่แผ่น',
    array['hammer strength shoulder press'], 'ไหล่', array['แขน'], 'เครื่อง', '⚙️',
    array['แขนสองข้างอิสระต่อกันดันขึ้นพร้อมกัน', 'กันข้างที่แข็งแรงกว่าชดเชยข้างที่อ่อนกว่า'],
    false, null, array['front-deltoids','triceps']),
  ('machine-rear-delt-fly', 'Machine Rear Delt Fly', 'แมชชีนเรียร์เดลต์ฟลาย',
    array['rear delt machine'], 'ไหล่', array['หลัง'], 'เครื่อง', '⚙️',
    array['หันหน้าเข้าเครื่อง กางแขนออกด้านหลัง', 'เน้นไหล่หลังและกล้ามหลังบนช่วงกลาง'],
    false, null, array['back-deltoids','upper-back']),

  -- ===== เคเบิล (7) =====
  ('cable-lateral-raise', 'Cable Lateral Raise', 'เคเบิลแลเทอรัลเรส',
    array['cable lateral raise'], 'ไหล่', array[]::text[], 'เคเบิล', '🔗',
    array['ยืนข้างรอกต่ำ ยกแขนออกด้านข้างข้ามลำตัว', 'แรงตึงคงที่กว่าดัมเบลตลอดจังหวะ'],
    false, null, array['front-deltoids']),
  ('cable-front-raise', 'Cable Front Raise', 'เคเบิลฟรอนต์เรส',
    array['cable front raise'], 'ไหล่', array[]::text[], 'เคเบิล', '🔗',
    array['ยืนหันหลังให้รอกต่ำ ยกแขนขึ้นตรงหน้า', 'แรงตึงคงที่ตลอดช่วงการเคลื่อนไหว'],
    false, null, array['front-deltoids']),
  ('cable-rear-delt-fly', 'Cable Rear Delt Fly', 'เคเบิลเรียร์เดลต์ฟลาย',
    array['cable rear delt fly'], 'ไหล่', array['หลัง'], 'เคเบิล', '🔗',
    array['ไขว้สายสองข้างจับตรงข้าม กางแขนออกด้านหลัง', 'เน้นไหล่หลังชัดกว่าดัมเบล'],
    false, null, array['back-deltoids','upper-back']),
  ('cable-y-raise', 'Cable Y-Raise', 'เคเบิลวายเรส',
    array['y raise'], 'ไหล่', array['หลัง'], 'เคเบิล', '🔗',
    array['ยกแขนสองข้างทำมุมตัว Y เฉียงขึ้น', 'ช่วยกล้ามหลังบนและไหล่ส่วนล่างที่มักถูกลืม'],
    false, null, array['front-deltoids','trapezius','upper-back']),
  ('single-arm-cable-lateral-raise', 'Single-Arm Cable Lateral Raise', 'เคเบิลแลเทอรัลเรสข้างเดียว',
    array['single arm cable lateral raise'], 'ไหล่', array[]::text[], 'เคเบิล', '🔗',
    array['ยืนข้างรอกต่ำ ยกแขนข้างเดียวออกด้านข้าง', 'ควบคุมฟอร์มง่ายกว่าทำสองข้างพร้อมกัน'],
    false, null, array['front-deltoids']),
  ('cable-shoulder-press', 'Cable Shoulder Press', 'เคเบิลโชลเดอร์เพรส',
    array['cable shoulder press'], 'ไหล่', array['แขน'], 'เคเบิล', '🔗',
    array['ยืนหรือนั่งดันด้ามจับขึ้นเหนือศีรษะจากรอกต่ำ', 'แรงตึงคงที่กว่าดัมเบล/บาร์เบลตลอดจังหวะ'],
    false, null, array['front-deltoids','triceps']),
  ('cable-external-rotation', 'Cable External Rotation', 'เคเบิลเอ็กซ์เทอร์นัลโรเทชัน',
    array['external rotation'], 'ไหล่', array[]::text[], 'เคเบิล', '🔗',
    array['ศอกแนบลำตัว หมุนแขนออกด้านนอกต้านแรงรอก', 'ท่าเสริมสุขภาพกล้ามหมุนไหล่ (rotator cuff) ใช้น้ำหนักเบา'],
    false, null, array['back-deltoids']),

  -- ===== น้ำหนักตัว (5) =====
  ('pike-push-up', 'Pike Push Up', 'ไพค์พุชอัพ',
    array['pike push up'], 'ไหล่', array['แขน'], 'น้ำหนักตัว', '🤸',
    array['ยกสะโพกสูงคล้ายท่า downward dog แล้วงอศอกลดหัวลงพื้น', 'พื้นฐานก่อนฝึก handstand push-up'],
    false, null, array['front-deltoids','triceps']),
  ('handstand-push-up', 'Handstand Push Up', 'แฮนด์สแตนด์พุชอัพ',
    array['handstand push up'], 'ไหล่', array['แขน'], 'น้ำหนักตัว', '🤸',
    array['ทำท่ายืนกลับหัวพิงกำแพง งอศอกลดหัวลงแตะพื้นแล้วดันขึ้น', 'ต้องการความแข็งแรงไหล่และความมั่นใจสูงมาก'],
    false, null, array['front-deltoids','triceps']),
  ('wall-walk', 'Wall Walk', 'วอลล์วอล์ค',
    array['wall walk'], 'ไหล่', array['แกนกลางลำตัว','แขน'], 'น้ำหนักตัว', '🤸',
    array['เริ่มจากท่าแพลงก์ เดินเท้าขึ้นกำแพงพร้อมเดินมือเข้าหากำแพง', 'ฝึกความแข็งแรงและความมั่นใจก่อนฝึก handstand'],
    false, null, array['front-deltoids','abs']),
  ('shoulder-tap-plank', 'Shoulder Tap Plank', 'โชลเดอร์แทปแพลงก์',
    array['plank shoulder tap'], 'ไหล่', array['แกนกลางลำตัว'], 'น้ำหนักตัว', '🤸',
    array['อยู่ในท่าแพลงก์แขนตรง สลับมือแตะไหล่ฝั่งตรงข้าม', 'คุมสะโพกไม่ให้แกว่งตามจังหวะแตะ'],
    false, null, array['front-deltoids','abs']),
  ('wall-slide', 'Wall Slide', 'วอลล์สไลด์',
    array['wall slide'], 'ไหล่', array['หลัง'], 'น้ำหนักตัว', '🤸',
    array['พิงหลังกับกำแพง แขนงอเป็นมุมฉากไถลขึ้น-ลงแนบกำแพง', 'ท่าฟื้นฟู/วอร์มอัพไหล่และกล้ามรอบสะบัก'],
    false, null, array['back-deltoids','upper-back'])
on conflict (id) do nothing;
