-- 019_exercise_library_seed_arms.sql
-- เพิ่มท่ากลุ่ม "แขน" อีก 32 ท่า (ของเดิมมี 8 ท่าอยู่แล้ว: barbell-curl, close-grip-bench-press,
-- dumbbell-curl, hammer-curl, overhead-triceps-extension, preacher-curl, skull-crusher,
-- triceps-pushdown — เช็คแล้วไม่ชนกับชุดนี้) ครอบคลุมทั้งไบเซ็ป/ไทรเซ็ป/แขนท่อนล่าง (forearm)
-- ครอบคลุม บาร์เบล(5) ดัมเบล(8) เครื่อง(5) เคเบิล(8) น้ำหนักตัว(6)
-- ON CONFLICT (id) DO NOTHING — รันซ้ำได้ปลอดภัย

insert into public.exercise_library
  (id, name, name_th, aliases, primary_muscle, secondary_muscles, equipment, icon, instructions, is_custom, image_url, highlighter_muscles)
values
  -- ===== บาร์เบล (5) =====
  ('ez-bar-curl', 'EZ-Bar Curl', 'อีซีบาร์เคิร์ล',
    array['ez bar curl'], 'แขน', array[]::text[], 'บาร์เบล', '🏋️',
    array['ใช้บาร์โค้งลดแรงบิดข้อมือ งอศอกยกขึ้น', 'เหมาะคนข้อมือไม่ถนัดจับบาร์ตรง'],
    false, null, array['biceps']),
  ('reverse-barbell-curl', 'Reverse Barbell Curl', 'รีเวิร์สบาร์เบลเคิร์ล',
    array['reverse curl'], 'แขน', array[]::text[], 'บาร์เบล', '🏋️',
    array['จับบาร์แบบมือคว่ำยกขึ้น', 'เน้นกล้ามแขนท่อนล่างมากกว่าจับหงาย'],
    false, null, array['forearm','biceps']),
  ('drag-curl', 'Drag Curl', 'แดร็กเคิร์ล',
    array['drag curl'], 'แขน', array[]::text[], 'บาร์เบล', '🏋️',
    array['ลากบาร์แนบลำตัวขึ้น ศอกถอยไปด้านหลังแทนการยกไปข้างหน้า', 'แยกไบเซ็ปออกจากไหล่ได้ชัดขึ้น'],
    false, null, array['biceps']),
  ('jm-press', 'JM Press', 'เจเอ็มเพรส',
    array['jm press'], 'แขน', array['อก'], 'บาร์เบล', '🏋️',
    array['ท่าผสมระหว่าง close-grip bench press กับ skull crusher ลดบาร์มาที่คาง', 'เน้นไทรเซ็ปหัวยาวได้ดี'],
    false, null, array['triceps','chest']),
  ('barbell-wrist-curl', 'Barbell Wrist Curl', 'บาร์เบลริสต์เคิร์ล',
    array['wrist curl'], 'แขน', array[]::text[], 'บาร์เบล', '🏋️',
    array['นั่งวางแขนบนขา ปล่อยข้อมืองอลง-กระดกขึ้น', 'เน้นกล้ามแขนท่อนล่างด้านใน'],
    false, null, array['forearm']),

  -- ===== ดัมเบล (8) =====
  ('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'อินไคลน์ดัมเบลเคิร์ล',
    array['incline curl'], 'แขน', array[]::text[], 'ดัมเบล', '💪',
    array['นั่งม้านั่งเอียงหลังพิงเต็มที่ แขนห้อยด้านหลังลำตัว', 'เพิ่ม ROM ยืดไบเซ็ปได้มากกว่านั่งตรง'],
    false, null, array['biceps']),
  ('concentration-curl', 'Concentration Curl', 'คอนเซนเทรชันเคิร์ล',
    array['concentration curl'], 'แขน', array[]::text[], 'ดัมเบล', '💪',
    array['นั่งศอกยันด้านในต้นขา งอศอกยกดัมเบลขึ้น', 'โฟกัสไบเซ็ปทีละข้างไม่มีแรงเหวี่ยง'],
    false, null, array['biceps']),
  ('zottman-curl', 'Zottman Curl', 'ซ็อตแมนเคิร์ล',
    array['zottman curl'], 'แขน', array[]::text[], 'ดัมเบล', '💪',
    array['ยกขึ้นแบบมือหงายปกติ แล้วหมุนมือคว่ำตอนปล่อยลง', 'ได้ทั้งไบเซ็ปตอนขึ้นและแขนท่อนล่างตอนลง'],
    false, null, array['biceps','forearm']),
  ('spider-curl', 'Spider Curl', 'สไปเดอร์เคิร์ล',
    array['spider curl'], 'แขน', array[]::text[], 'ดัมเบล', '💪',
    array['นอนคว่ำบนม้านั่งเอียงชัน แขนห้อยตรงหน้า งอศอกยกขึ้น', 'ตัดแรงเหวี่ยงจากลำตัวเกือบหมด'],
    false, null, array['biceps']),
  ('dumbbell-kickback', 'Dumbbell Triceps Kickback', 'ดัมเบลคิกแบ็ค',
    array['triceps kickback'], 'แขน', array[]::text[], 'ดัมเบล', '💪',
    array['ก้มตัวศอกแนบลำตัวชี้ไปด้านหลัง เหยียดแขนตรง', 'คุมจังหวะกลับช้าๆ ไม่แกว่ง'],
    false, null, array['triceps']),
  ('dumbbell-wrist-curl', 'Dumbbell Wrist Curl', 'ดัมเบลริสต์เคิร์ล',
    array['dumbbell wrist curl'], 'แขน', array[]::text[], 'ดัมเบล', '💪',
    array['นั่งวางแขนบนขา ปล่อยข้อมืองอลง-กระดกขึ้นทีละข้าง', 'ปรับน้ำหนักได้ละเอียดกว่าบาร์เบล'],
    false, null, array['forearm']),
  ('reverse-dumbbell-curl', 'Reverse Dumbbell Curl', 'รีเวิร์สดัมเบลเคิร์ล',
    array['reverse dumbbell curl'], 'แขน', array[]::text[], 'ดัมเบล', '💪',
    array['จับดัมเบลมือคว่ำยกขึ้น', 'เน้นกล้ามแขนท่อนล่างเป็นหลัก'],
    false, null, array['forearm','biceps']),
  ('cross-body-hammer-curl', 'Cross-Body Hammer Curl', 'ครอสบอดี้แฮมเมอร์เคิร์ล',
    array['cross body hammer curl'], 'แขน', array[]::text[], 'ดัมเบล', '💪',
    array['จับมือคว่ำขนาน ยกดัมเบลเข้าหาไหล่ฝั่งตรงข้ามแทนตรงหน้า', 'มุมยกต่างช่วยกระตุ้นกล้ามหัวยาวมากขึ้น'],
    false, null, array['biceps','forearm']),

  -- ===== เครื่อง (5) =====
  ('preacher-curl-machine', 'Preacher Curl Machine', 'แมชชีนพรีชเชอร์เคิร์ล',
    array['preacher curl machine'], 'แขน', array[]::text[], 'เครื่อง', '⚙️',
    array['วางแขนบนเบาะเอียง งอศอกดึงด้ามจับขึ้น', 'ตัดแรงเหวี่ยงลำตัวเหมือน preacher curl แบบม้านั่ง'],
    false, null, array['biceps']),
  ('bicep-curl-machine', 'Bicep Curl Machine', 'แมชชีนไบเซ็ปเคิร์ล',
    array['bicep curl machine'], 'แขน', array[]::text[], 'เครื่อง', '⚙️',
    array['นั่งวางแขนบนเบาะรอง งอศอกดึงด้ามจับขึ้น', 'แรงต้านคงที่ตลอดจังหวะ'],
    false, null, array['biceps']),
  ('triceps-extension-machine', 'Triceps Extension Machine', 'แมชชีนไทรเซ็ปเอ็กซ์เทนชัน',
    array['triceps extension machine'], 'แขน', array[]::text[], 'เครื่อง', '⚙️',
    array['นั่งดันด้ามจับลงด้วยการเหยียดศอก', 'ปรับเบาะให้ศอกอยู่แนวเดียวกับจุดหมุนเครื่อง'],
    false, null, array['triceps']),
  ('assisted-dip-machine', 'Assisted Dip Machine', 'แมชชีนช่วยดิป',
    array['assisted dip'], 'แขน', array['อก','ไหล่'], 'เครื่อง', '⚙️',
    array['ปรับน้ำหนักถ่วงช่วยตามระดับความแข็งแรง ดันตัวขึ้น-ลงในท่าดิป', 'เหมาะฝึกก่อนทำดิปด้วยน้ำหนักตัวเต็มๆ'],
    false, null, array['triceps','chest']),
  ('reverse-curl-machine', 'Reverse Curl Machine', 'แมชชีนรีเวิร์สเคิร์ล',
    array['reverse curl machine'], 'แขน', array[]::text[], 'เครื่อง', '⚙️',
    array['จับด้ามแบบมือคว่ำ งอศอกดึงขึ้น', 'เน้นแขนท่อนล่างในเครื่องที่คุมฟอร์มได้ง่าย'],
    false, null, array['forearm','biceps']),

  -- ===== เคเบิล (8) =====
  ('cable-curl', 'Cable Curl', 'เคเบิลเคิร์ล',
    array['cable curl'], 'แขน', array[]::text[], 'เคเบิล', '🔗',
    array['ยืนหน้ารอกต่ำ ใช้บาร์ตรง/EZ งอศอกดึงขึ้น', 'แรงตึงคงที่กว่าดัมเบล/บาร์เบลตลอดจังหวะ'],
    false, null, array['biceps']),
  ('rope-hammer-curl', 'Rope Hammer Curl', 'โรปแฮมเมอร์เคิร์ล',
    array['rope hammer curl'], 'แขน', array[]::text[], 'เคเบิล', '🔗',
    array['ใช้ด้ามเชือกจับคว่ำขนาน ดึงขึ้นหาไหล่', 'เน้นหัวไบเซ็ปด้านนอกและแขนท่อนล่าง'],
    false, null, array['biceps','forearm']),
  ('cable-overhead-triceps-extension', 'Cable Overhead Triceps Extension', 'เคเบิลโอเวอร์เฮดไทรเซ็ปเอ็กซ์เทนชัน',
    array['overhead cable extension'], 'แขน', array[]::text[], 'เคเบิล', '🔗',
    array['หันหลังให้รอกต่ำ ยกศอกเหนือศีรษะเหยียดแขนไปข้างหน้า', 'ยืดไทรเซ็ปหัวยาวได้มากกว่า pushdown'],
    false, null, array['triceps']),
  ('single-arm-cable-triceps-extension', 'Single-Arm Cable Triceps Extension', 'เคเบิลไทรเซ็ปเอ็กซ์เทนชันข้างเดียว',
    array['single arm triceps extension'], 'แขน', array[]::text[], 'เคเบิล', '🔗',
    array['ยืนข้างรอกสูง เหยียดแขนลงทีละข้าง', 'แก้ปัญหาข้างที่ไม่สมดุลกันได้ดี'],
    false, null, array['triceps']),
  ('reverse-grip-triceps-pushdown', 'Reverse-Grip Triceps Pushdown', 'ทริเซ็ปพุชดาวน์จับหงาย',
    array['reverse grip pushdown'], 'แขน', array[]::text[], 'เคเบิล', '🔗',
    array['จับบาร์แบบมือหงายกดลง', 'เน้นไทรเซ็ปหัวในมากกว่าจับคว่ำปกติ'],
    false, null, array['triceps']),
  ('cable-concentration-curl', 'Cable Concentration Curl', 'เคเบิลคอนเซนเทรชันเคิร์ล',
    array['cable concentration curl'], 'แขน', array[]::text[], 'เคเบิล', '🔗',
    array['นั่งศอกยันต้นขาดึงด้ามจับรอกต่ำขึ้น', 'แรงตึงคงที่กว่าดัมเบลตลอดจังหวะ'],
    false, null, array['biceps']),
  ('bayesian-cable-curl', 'Bayesian Cable Curl', 'เบย์เซียนเคเบิลเคิร์ล',
    array['bayesian curl'], 'แขน', array[]::text[], 'เคเบิล', '🔗',
    array['ยืนหันหลังให้รอกต่ำ แขนเหยียดไปด้านหลังลำตัวก่อนงอศอกยกขึ้น', 'ยืดไบเซ็ปตอนเริ่มต้นได้มากเป็นพิเศษ'],
    false, null, array['biceps']),
  ('cable-wrist-curl', 'Cable Wrist Curl', 'เคเบิลริสต์เคิร์ล',
    array['cable wrist curl'], 'แขน', array[]::text[], 'เคเบิล', '🔗',
    array['คุกเข่าหรือนั่งวางแขนบนขา ปล่อยข้อมืองอลง-กระดกขึ้นดึงเชือกจากรอกต่ำ', 'แรงตึงคงที่กว่าดัมเบลตลอดจังหวะ'],
    false, null, array['forearm']),

  -- ===== น้ำหนักตัว (6) =====
  ('bench-dip', 'Bench Dip', 'เบนช์ดิป',
    array['bench dip'], 'แขน', array['อก','ไหล่'], 'น้ำหนักตัว', '🤸',
    array['มือยันขอบม้านั่งด้านหลังลำตัว งอศอกลดสะโพกลง', 'เพิ่มความยากด้วยการยกเท้าสูงหรือวางน้ำหนักบนตัก'],
    false, null, array['triceps','chest']),
  ('bodyweight-curl', 'Bodyweight Curl', 'บอดี้เวทเคิร์ล',
    array['inverted curl'], 'แขน', array['หลัง'], 'น้ำหนักตัว', '🤸',
    array['จับบาร์ต่ำเอนตัวไปด้านหลัง งอศอกดึงตัวขึ้นแบบเน้นไบเซ็ป', 'คล้าย inverted row แต่เน้นมุมงอศอกมากกว่าดึงหลัง'],
    false, null, array['biceps','upper-back']),
  ('wrist-roller', 'Wrist Roller', 'ริสต์โรลเลอร์',
    array['wrist roller'], 'แขน', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['ใช้แท่งไม้ผูกเชือกถ่วงน้ำหนัก หมุนข้อมือม้วนเชือกขึ้น-ลง', 'ฝึกความแข็งแรงแขนท่อนล่างและแรงจับ'],
    false, null, array['forearm']),
  ('plate-pinch', 'Plate Pinch', 'เพลทพินช์',
    array['plate pinch'], 'แขน', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['หนีบแผ่นน้ำหนัก 2 แผ่นด้วยปลายนิ้วถือค้างไว้ให้นานที่สุด', 'ฝึกแรงบีบนิ้วและแขนท่อนล่างโดยตรง'],
    false, null, array['forearm']),
  ('fingertip-push-up', 'Fingertip Push Up', 'ฟิงเกอร์ทิปพุชอัพ',
    array['fingertip push up'], 'แขน', array['อก','ไหล่'], 'น้ำหนักตัว', '🤸',
    array['พุชอัพโดยใช้ปลายนิ้วรับน้ำหนักแทนฝ่ามือทั้งหมด', 'เพิ่มความแข็งแรงนิ้ว/แขนท่อนล่างไปพร้อมอกและไหล่'],
    false, null, array['forearm','triceps','chest']),
  ('dead-hang', 'Dead Hang', 'เดดแฮง',
    array['dead hang'], 'แขน', array['หลัง'], 'น้ำหนักตัว', '🤸',
    array['ห้อยตัวที่บาร์เต็มแขนค้างไว้ให้นานที่สุด', 'ฝึกแรงจับและยืดกระดูกสันหลัง/ไหล่ไปพร้อมกัน'],
    false, null, array['forearm','upper-back'])
on conflict (id) do nothing;
