-- 020_exercise_library_seed_core.sql
-- เพิ่มท่ากลุ่ม "แกนกลางลำตัว" อีก 29 ท่า (ของเดิมมี 6 ท่าอยู่แล้ว: ab-wheel-rollout, cable-crunch,
-- hanging-leg-raise, plank, russian-twist, sit-up — เช็คแล้วไม่ชนกับชุดนี้)
-- ครอบคลุม บาร์เบล(2) ดัมเบล(4) เครื่อง(3) เคเบิล(6) น้ำหนักตัว(12) คีทเทิลเบล(2)
-- ON CONFLICT (id) DO NOTHING — รันซ้ำได้ปลอดภัย

insert into public.exercise_library
  (id, name, name_th, aliases, primary_muscle, secondary_muscles, equipment, icon, instructions, is_custom, image_url, highlighter_muscles)
values
  -- ===== บาร์เบล (2) =====
  ('barbell-rollout', 'Barbell Rollout', 'บาร์เบลโรลเอาท์',
    array['barbell rollout'], 'แกนกลางลำตัว', array['ไหล่'], 'บาร์เบล', '🏋️',
    array['คุกเข่าจับบาร์มีแผ่นเล็กสองข้าง กลิ้งออกไปข้างหน้าจนลำตัวเกือบขนานพื้นแล้วดึงกลับ', 'หนักกว่า ab wheel เพราะคุมสมดุลยากกว่า'],
    false, null, array['abs','front-deltoids']),
  ('landmine-rotation', 'Landmine Rotation', 'แลนด์ไมน์โรเทชัน',
    array['landmine 180', 'landmine rotation'], 'แกนกลางลำตัว', array['ไหล่'], 'บาร์เบล', '🏋️',
    array['ปักปลายบาร์กับมุม/landmine ถือปลายอีกด้านหมุนลำตัวสลับข้าง', 'ฝึกพลังหมุนตัวที่ใช้ในกีฬาหลายชนิด'],
    false, null, array['obliques','abs']),

  -- ===== ดัมเบล (4) =====
  ('dumbbell-side-bend', 'Dumbbell Side Bend', 'ดัมเบลไซด์เบนด์',
    array['side bend'], 'แกนกลางลำตัว', array[]::text[], 'ดัมเบล', '💪',
    array['ถือดัมเบลข้างเดียวเอนตัวลงด้านข้างแล้วดึงกลับขึ้น', 'เน้นกล้ามเอียงข้างลำตัว (obliques)'],
    false, null, array['obliques']),
  ('weighted-sit-up', 'Weighted Sit Up', 'เวทเต็ดซิทอัพ',
    array['weighted sit up'], 'แกนกลางลำตัว', array[]::text[], 'ดัมเบล', '💪',
    array['นอนหงายชันเข่าถือดัมเบล/แผ่นน้ำหนักแนบอก ลุกขึ้นนั่ง', 'เพิ่มความหนักให้ท่าซิทอัพพื้นฐาน'],
    false, null, array['abs']),
  ('dumbbell-woodchopper', 'Dumbbell Woodchopper', 'ดัมเบลวูดช็อปเปอร์',
    array['dumbbell woodchopper'], 'แกนกลางลำตัว', array['ไหล่'], 'ดัมเบล', '💪',
    array['ถือดัมเบลสองมือ หมุนลำตัวจากสูงลงต่ำทแยงมุมคล้ายฟันไม้', 'ฝึกกล้ามแกนกลางแบบหมุนตัว'],
    false, null, array['obliques','abs']),
  ('suitcase-carry', 'Suitcase Carry', 'สูทเคสแคร์รี่',
    array['suitcase carry'], 'แกนกลางลำตัว', array['หลัง'], 'ดัมเบล', '💪',
    array['ถือดัมเบลหนักข้างเดียวเดินคุมลำตัวให้ตรง ไม่เอียงตาม', 'ฝึกความมั่นคงของแกนกลางแบบต้านการเอียงตัว'],
    false, null, array['obliques','forearm','lower-back']),

  -- ===== เครื่อง (3) =====
  ('ab-crunch-machine', 'Ab Crunch Machine', 'แมชชีนแอบครันช์',
    array['ab crunch machine'], 'แกนกลางลำตัว', array[]::text[], 'เครื่อง', '⚙️',
    array['นั่งจับด้ามจับเหนือศีรษะ ก้มตัวงอลำตัวลง', 'แรงต้านคงที่กว่าซิทอัพ/ครันช์พื้น'],
    false, null, array['abs']),
  ('rotary-torso-machine', 'Rotary Torso Machine', 'แมชชีนโรทารีทอร์โซ',
    array['rotary torso machine'], 'แกนกลางลำตัว', array[]::text[], 'เครื่อง', '⚙️',
    array['นั่งล็อกสะโพกกับเบาะ หมุนลำตัวช่วงบนสลับข้าง', 'แยกกล้ามเอียงข้างลำตัวได้ชัดเจน'],
    false, null, array['obliques']),
  ('captains-chair-leg-raise', "Captain's Chair Leg Raise", 'แคปเทนส์แชร์เลกเรส',
    array['captains chair'], 'แกนกลางลำตัว', array[]::text[], 'เครื่อง', '⚙️',
    array['พยุงตัวด้วยแขนบนที่รองศอก ยกขาขึ้นงอเข่าหรือเหยียดตรง', 'คล้าย hanging leg raise แต่มีที่พยุงแขนช่วยลดภาระไหล่'],
    false, null, array['abs']),

  -- ===== เคเบิล (6) =====
  ('cable-woodchopper', 'Cable Woodchopper', 'เคเบิลวูดช็อปเปอร์',
    array['cable woodchopper'], 'แกนกลางลำตัว', array['ไหล่'], 'เคเบิล', '🔗',
    array['ตั้งรอกสูง ดึงลงมาทแยงต่ำสุดฝั่งตรงข้าม พร้อมหมุนลำตัว', 'จำลองการเคลื่อนไหวแบบฟันไม้'],
    false, null, array['obliques','abs']),
  ('cable-reverse-woodchopper', 'Cable Reverse Woodchopper', 'เคเบิลรีเวิร์สวูดช็อปเปอร์',
    array['reverse woodchopper'], 'แกนกลางลำตัว', array['ไหล่'], 'เคเบิล', '🔗',
    array['ตั้งรอกต่ำ ดึงขึ้นทแยงสูงฝั่งตรงข้าม พร้อมหมุนลำตัว', 'ทิศทางตรงข้ามกับ woodchopper ปกติ'],
    false, null, array['obliques','abs']),
  ('pallof-press', 'Pallof Press', 'พาลอฟเพรส',
    array['pallof press', 'anti rotation press'], 'แกนกลางลำตัว', array[]::text[], 'เคเบิล', '🔗',
    array['ยืนข้างรอก ถือด้ามจับแนบอกดันออกตรงหน้าต้านแรงบิดตัว', 'ฝึกความมั่นคงแบบต้านการหมุน (anti-rotation)'],
    false, null, array['abs','obliques']),
  ('cable-side-bend', 'Cable Side Bend', 'เคเบิลไซด์เบนด์',
    array['cable side bend'], 'แกนกลางลำตัว', array[]::text[], 'เคเบิล', '🔗',
    array['ยืนข้างรอกต่ำถือด้ามจับ เอนตัวลงด้านข้างแล้วดึงกลับขึ้น', 'แรงตึงคงที่กว่าดัมเบลตลอดจังหวะ'],
    false, null, array['obliques']),
  ('standing-cable-crunch', 'Standing Cable Crunch', 'ยืนเคเบิลครันช์',
    array['standing cable crunch'], 'แกนกลางลำตัว', array[]::text[], 'เคเบิล', '🔗',
    array['ยืนหันหลังให้รอกสูง ถือเชือกข้างศีรษะ ก้มตัวงอลำตัวลง', 'ทางเลือกแทนท่าคุกเข่าครันช์'],
    false, null, array['abs']),
  ('cable-lift', 'Cable Lift', 'เคเบิลลิฟต์',
    array['cable lift'], 'แกนกลางลำตัว', array['ไหล่'], 'เคเบิล', '🔗',
    array['ตั้งรอกต่ำ ดึงขึ้นทแยงสูงโดยแขนตรง ไม่หมุนลำตัวมาก', 'ต่างจาก woodchopper ที่เน้นหมุนตัวมากกว่า'],
    false, null, array['obliques','abs']),

  -- ===== น้ำหนักตัว (12) =====
  ('mountain-climber', 'Mountain Climber', 'เมาน์เทนไคลม์เบอร์',
    array['mountain climber'], 'แกนกลางลำตัว', array['ไหล่'], 'น้ำหนักตัว', '🤸',
    array['อยู่ในท่าแพลงก์ สลับดึงเข่าเข้าหาอกเร็วๆ', 'ได้ทั้งแกนกลางและคาร์ดิโอไปพร้อมกัน'],
    false, null, array['abs','front-deltoids']),
  ('bicycle-crunch', 'Bicycle Crunch', 'ไบซิเคิลครันช์',
    array['bicycle crunch'], 'แกนกลางลำตัว', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['นอนหงายมือประสานท้ายทอย ปั่นขาสลับพร้อมบิดศอกแตะเข่าฝั่งตรงข้าม', 'เน้นทั้ง abs และกล้ามเอียงข้างลำตัว'],
    false, null, array['abs','obliques']),
  ('leg-raise', 'Lying Leg Raise', 'ไลอิ้งเลกเรส',
    array['leg raise'], 'แกนกลางลำตัว', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['นอนหงายขาตรง ยกขาขึ้น 90 องศาแล้วลดลงช้าๆ ไม่ให้แตะพื้น', 'เน้น abs ส่วนล่าง'],
    false, null, array['abs']),
  ('flutter-kick', 'Flutter Kick', 'ฟลัตเตอร์คิก',
    array['flutter kick'], 'แกนกลางลำตัว', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['นอนหงายยกขาลอยเตี้ยๆ สลับตีขาขึ้นลงเร็วๆ', 'เน้นความอึดของ abs ส่วนล่าง'],
    false, null, array['abs']),
  ('v-up', 'V-Up', 'วียูพ',
    array['v up'], 'แกนกลางลำตัว', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['นอนหงายยกแขนและขาพร้อมกันให้มาบรรจบเป็นรูปตัว V', 'ต้องการความแข็งแรงของ abs สูง'],
    false, null, array['abs']),
  ('side-plank', 'Side Plank', 'ไซด์แพลงก์',
    array['side plank'], 'แกนกลางลำตัว', array['ไหล่'], 'น้ำหนักตัว', '🤸',
    array['นอนตะแคงยันศอกยกสะโพกลอยเป็นเส้นตรง', 'ค้างไว้ให้นานที่สุดแต่ละข้าง'],
    false, null, array['obliques','front-deltoids']),
  ('hollow-body-hold', 'Hollow Body Hold', 'ฮอลโลว์บอดี้โฮลด์',
    array['hollow hold'], 'แกนกลางลำตัว', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['นอนหงายยกไหล่และขาลอยพร้อมกัน หลังส่วนล่างแนบพื้นตลอด', 'ท่าพื้นฐานของยิมนาสติกที่ฝึกแกนกลางทั้งตัว'],
    false, null, array['abs']),
  ('dead-bug', 'Dead Bug', 'เดดบั๊ก',
    array['dead bug'], 'แกนกลางลำตัว', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['นอนหงายยกแขน-ขาขึ้น 90 องศา ยื่นแขนและขาตรงข้ามลงพร้อมกันสลับข้าง', 'หลังส่วนล่างแนบพื้นตลอด ปลอดภัยกับหลัง'],
    false, null, array['abs']),
  ('toe-touch', 'Toe Touch', 'โท้ทัช',
    array['toe touch'], 'แกนกลางลำตัว', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['นอนหงายยกขาตรงขึ้น 90 องศา เอื้อมมือแตะปลายเท้า', 'เน้น abs ส่วนบน'],
    false, null, array['abs']),
  ('reverse-crunch', 'Reverse Crunch', 'รีเวิร์สครันช์',
    array['reverse crunch'], 'แกนกลางลำตัว', array[]::text[], 'น้ำหนักตัว', '🤸',
    array['นอนหงายชันเข่า ยกสะโพกขึ้นเข้าหาอกแทนการยกช่วงบน', 'เน้น abs ส่วนล่าง'],
    false, null, array['abs']),
  ('dragon-flag', 'Dragon Flag', 'ดราก้อนแฟลก',
    array['dragon flag'], 'แกนกลางลำตัว', array['หลัง'], 'น้ำหนักตัว', '🤸',
    array['นอนหงายจับขอบม้านั่งเหนือศีรษะ ยกลำตัวทั้งท่อนขึ้นตรงเป็นเส้นเดียว แล้วลดลงช้าๆ', 'ท่ายากมาก ต้องฝึกพื้นฐานให้แข็งแรงก่อน'],
    false, null, array['abs','lower-back']),
  ('plank-up-down', 'Plank Up-Down', 'แพลงก์อัพดาวน์',
    array['plank up down'], 'แกนกลางลำตัว', array['ไหล่','แขน'], 'น้ำหนักตัว', '🤸',
    array['อยู่ในท่าแพลงก์ สลับลงศอกและดันขึ้นเป็นแพลงก์แขนตรง', 'เพิ่มความแข็งแรงแขน/ไหล่ไปพร้อมแกนกลาง'],
    false, null, array['abs','triceps']),

  -- ===== คีทเทิลเบล (2) =====
  ('kettlebell-windmill', 'Kettlebell Windmill', 'เคทเทิลเบลวินด์มิลล์',
    array['windmill'], 'แกนกลางลำตัว', array['หลัง','ไหล่'], 'คีทเทิลเบล', '🔔',
    array['ยกเคทเทิลเบลเหนือศีรษะข้างเดียว ก้มสะโพกลงด้านข้างมืออีกข้างแตะพื้น', 'ฝึกความมั่นคงแกนกลางพร้อมความยืดหยุ่นสะโพก'],
    false, null, array['obliques','lower-back','front-deltoids']),
  ('turkish-get-up', 'Turkish Get-Up', 'เตอร์กิชเก็ตอัพ',
    array['turkish get up', 'tgu'], 'แกนกลางลำตัว', array['ไหล่','ขา'], 'คีทเทิลเบล', '🔔',
    array['เริ่มจากนอนถือเคทเทิลเบลเหนือศีรษะ ลุกขึ้นยืนทีละขั้นตอนโดยแขนล็อกตลอด', 'ท่าซับซ้อนฝึกทั้งแกนกลาง ไหล่ และการทรงตัว'],
    false, null, array['abs','front-deltoids','quadriceps'])
on conflict (id) do nothing;
