-- 022_exercise_library_seed_other.sql
-- เพิ่มท่ากลุ่ม "อื่นๆ" 20 ท่า (ของเดิมยังไม่มีท่าในกลุ่มนี้เลย) — เป็นท่ายืดเหยียด/มือถือ/วอร์มอัพ
-- ที่ไม่ผูกกับกล้ามเนื้อกลุ่มใดกลุ่มหนึ่งชัดเจน ใช้คู่กับ Timer (Warm-up) หรือ cool-down หลังฝึก
-- equipment ทั้งหมดเป็น 'น้ำหนักตัว' เพราะ Equipment type ของระบบยังไม่มีหมวด
-- ยางยืด/โฟมโรลเลอร์แยกต่างหาก (ใช้ของเหล่านี้ประกอบได้แต่ไม่บังคับ)
-- ON CONFLICT (id) DO NOTHING — รันซ้ำได้ปลอดภัย

insert into public.exercise_library
  (id, name, name_th, aliases, primary_muscle, secondary_muscles, equipment, icon, instructions, is_custom, image_url, highlighter_muscles)
values
  ('cat-cow-stretch', 'Cat-Cow Stretch', 'คว่ำ-แมวยืดหลัง',
    array['cat cow'], 'อื่นๆ', array['หลัง'], 'น้ำหนักตัว', '🧘',
    array['คุกเข่ามือยันพื้น สลับแอ่นหลังลง-โก่งหลังขึ้นช้าๆ', 'คลายกล้ามหลังและเพิ่มความยืดหยุ่นของกระดูกสันหลัง'],
    false, null, array['lower-back','upper-back']),
  ('worlds-greatest-stretch', "World's Greatest Stretch", 'เวิลด์เกรทเทสต์สเตรทช์',
    array['worlds greatest stretch'], 'อื่นๆ', array['ขา'], 'น้ำหนักตัว', '🧘',
    array['ก้าวขาลันจ์ยาว มือแตะพื้นข้างเท้าแล้วหมุนแขนขึ้นฟ้า', 'ยืดสะโพก ต้นขา และหลังส่วนบนในท่าเดียว'],
    false, null, array['quadriceps','hamstring','adductor']),
  ('hip-flexor-stretch', 'Hip Flexor Stretch', 'สเตรทช์สะโพกงอ',
    array['couch stretch'], 'อื่นๆ', array['ขา'], 'น้ำหนักตัว', '🧘',
    array['คุกเข่าหลัง วางเท้าหลังบนที่สูง โน้มสะโพกไปข้างหน้า', 'ยืดกล้ามสะโพกงอและต้นขาหน้า'],
    false, null, array['quadriceps']),
  ('pigeon-pose', 'Pigeon Pose', 'ท่านกพิราบ',
    array['pigeon pose'], 'อื่นๆ', array['ขา'], 'น้ำหนักตัว', '🧘',
    array['งอเข่าหน้าขวางลำตัว เหยียดขาหลังตรงไปด้านหลัง โน้มตัวลง', 'ยืดกล้ามสะโพกและก้นลึก'],
    false, null, array['gluteal','adductor']),
  ('thoracic-spine-rotation', 'Thoracic Spine Rotation', 'หมุนกระดูกสันหลังช่วงอก',
    array['t spine rotation'], 'อื่นๆ', array['หลัง'], 'น้ำหนักตัว', '🧘',
    array['คุกเข่ามือหนึ่งยันพื้น อีกมือแตะท้ายทอยหมุนลำตัวเปิดขึ้นฟ้า', 'เพิ่มความยืดหยุ่นการหมุนตัวช่วงอก'],
    false, null, array['obliques','upper-back']),
  ('arm-circles', 'Arm Circles', 'หมุนแขนเป็นวงกลม',
    array['arm circles'], 'อื่นๆ', array['ไหล่'], 'น้ำหนักตัว', '🧘',
    array['กางแขนตรงข้างลำตัว หมุนเป็นวงกลมเล็กไปใหญ่ทั้งสองทิศทาง', 'วอร์มอัพข้อไหล่ก่อนฝึกท่าดันหรือดึง'],
    false, null, array['front-deltoids','back-deltoids']),
  ('leg-swings', 'Leg Swings', 'แกว่งขา',
    array['leg swings'], 'อื่นๆ', array['ขา'], 'น้ำหนักตัว', '🧘',
    array['จับที่ยึดแกว่งขาหน้า-หลังและซ้าย-ขวาสลับกัน', 'วอร์มอัพสะโพกและต้นขาก่อนฝึกขา'],
    false, null, array['hamstring','adductor']),
  ('inchworm', 'Inchworm', 'อินช์เวิร์ม',
    array['inchworm'], 'อื่นๆ', array['แกนกลางลำตัว','ขา'], 'น้ำหนักตัว', '🧘',
    array['ยืนก้มตัวมือเดินไปข้างหน้าจนถึงท่าแพลงก์ แล้วเดินเท้าตามมือกลับมา', 'ยืดหลังต้นขาไปพร้อมวอร์มอัพแกนกลาง'],
    false, null, array['hamstring','abs']),
  ('jumping-jacks', 'Jumping Jacks', 'จั๊มพ์ปิ้งแจ็ค',
    array['jumping jacks'], 'อื่นๆ', array['ขา','ไหล่'], 'น้ำหนักตัว', '🧘',
    array['กระโดดกางแขน-ขาพร้อมกันแล้วกลับท่ายืนตรง', 'วอร์มอัพคาร์ดิโอเบาๆ ทั้งตัวก่อนฝึกหนัก'],
    false, null, array['quadriceps','calves','front-deltoids']),
  ('high-knees', 'High Knees', 'ไฮนีส์',
    array['high knees'], 'อื่นๆ', array['ขา'], 'น้ำหนักตัว', '🧘',
    array['วิ่งอยู่กับที่ยกเข่าสูงระดับสะโพกสลับข้างเร็วๆ', 'วอร์มอัพขาและเพิ่มอัตราการเต้นของหัวใจ'],
    false, null, array['quadriceps','calves']),
  ('butt-kicks', 'Butt Kicks', 'บัตต์คิกส์',
    array['butt kicks'], 'อื่นๆ', array['ขา'], 'น้ำหนักตัว', '🧘',
    array['วิ่งอยู่กับที่เตะส้นเท้าแตะก้นสลับข้างเร็วๆ', 'วอร์มอัพกล้ามหลังต้นขาและน่อง'],
    false, null, array['hamstring','calves']),
  ('jump-rope', 'Jump Rope', 'กระโดดเชือก',
    array['jump rope', 'skipping rope'], 'อื่นๆ', array['ขา'], 'น้ำหนักตัว', '🧘',
    array['กระโดดข้ามเชือกด้วยปลายเท้าเบาๆ จังหวะสม่ำเสมอ', 'ฝึกคาร์ดิโอเบาๆ และความไวของข้อเท้าไปพร้อมกัน'],
    false, null, array['calves','quadriceps']),
  ('foam-rolling-quads', 'Foam Rolling (Quads)', 'โฟมโรลลิ่งต้นขาหน้า',
    array['foam rolling'], 'อื่นๆ', array['ขา'], 'น้ำหนักตัว', '🧘',
    array['นอนคว่ำวางต้นขาบนโฟมโรลเลอร์ กลิ้งไป-มาช้าๆ กดจุดที่ตึง', 'คลายกล้ามเนื้อและพังผืดหลังฝึก'],
    false, null, array['quadriceps']),
  ('downward-dog', 'Downward Dog', 'ท่าสุนัขก้มหน้า',
    array['downward facing dog'], 'อื่นๆ', array['ขา','ไหล่'], 'น้ำหนักตัว', '🧘',
    array['มือและเท้ายันพื้น ดันสะโพกขึ้นสูงเป็นรูปตัว V คว่ำ', 'ยืดหลังต้นขา น่อง และไหล่ไปพร้อมกัน'],
    false, null, array['hamstring','front-deltoids']),
  ('childs-pose', "Child's Pose", 'ท่าเด็กทารก',
    array['child pose'], 'อื่นๆ', array['หลัง'], 'น้ำหนักตัว', '🧘',
    array['คุกเข่านั่งบนส้นเท้า โน้มตัวยื่นแขนไปข้างหน้าแนบพื้น', 'ผ่อนคลายหลังส่วนล่างหลังฝึกหนัก'],
    false, null, array['lower-back']),
  ('cossack-squat', 'Cossack Squat', 'ค็อสแซคสควอท',
    array['cossack squat'], 'อื่นๆ', array['ขา'], 'น้ำหนักตัว', '🧘',
    array['ยืนขากว้าง ย่อตัวไปข้างเดียวขาอีกข้างเหยียดตรง สลับข้าง', 'เพิ่มความยืดหยุ่นสะโพกไปพร้อมความแข็งแรงของขา'],
    false, null, array['adductor','quadriceps','gluteal']),
  ('shoulder-dislocates', 'Shoulder Dislocates', 'โชลเดอร์ดิสโลเคต',
    array['shoulder dislocates'], 'อื่นๆ', array['ไหล่'], 'น้ำหนักตัว', '🧘',
    array['จับปลายไม้/ยางยืดสองมือกว้างกว่าไหล่ ยกวนจากหน้าไปหลังศีรษะ', 'เพิ่มความยืดหยุ่นข้อไหล่ก่อนฝึกท่าเพรส'],
    false, null, array['front-deltoids','back-deltoids']),
  ('ankle-circles', 'Ankle Circles', 'หมุนข้อเท้า',
    array['ankle circles'], 'อื่นๆ', array[]::text[], 'น้ำหนักตัว', '🧘',
    array['ยกเท้าลอยหมุนข้อเท้าเป็นวงกลมทั้งสองทิศทาง', 'วอร์มอัพข้อเท้าก่อนฝึกขาหรือกระโดด'],
    false, null, array['calves']),
  ('spiderman-lunge-stretch', 'Spiderman Lunge Stretch', 'สไปเดอร์แมนลันจ์สเตรทช์',
    array['spiderman lunge'], 'อื่นๆ', array['ขา'], 'น้ำหนักตัว', '🧘',
    array['ก้าวขาลันจ์ต่ำ วางมือทั้งสองข้างในเท้าหน้าแล้วหมุนลำตัวเปิดข้าง', 'ยืดสะโพกและต้นขาด้านในไปพร้อมหมุนตัว'],
    false, null, array['adductor','quadriceps']),
  ('standing-quad-stretch', 'Standing Quad Stretch', 'ยืนยืดต้นขาหน้า',
    array['standing quad stretch'], 'อื่นๆ', array['ขา'], 'น้ำหนักตัว', '🧘',
    array['ยืนขาเดียว จับข้อเท้าอีกข้างดึงส้นเท้าเข้าหาก้น', 'ยืดกล้ามต้นขาหน้าก่อนหรือหลังฝึกขา'],
    false, null, array['quadriceps'])
on conflict (id) do nothing;
